<?php $this->headScript()->appendFile($this->baseUrl().'/js/chamados/index.js')?>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Chamados ::.</h3>
	</div>
</div>
	<?php if( $this->vencidos ) : ?>
    <div class="alert alert-info">
        <h4 class="alert-heading">Exite(m) <span class="badge badge-warning"><?php echo $this->vencidos?></span> Chamados com SLA vencido! <span id='slaVencido' class="badge badge-error">ver</span></h4>
        
      </div>
    <?php endif;?>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php //echo $_SESSION['message']?></h4>
    	Nro. do protocolo: <span class="badge badge-info"><?php echo $this->protocolo;?></span>
    </div>
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php //echo $_SESSION['message'];?>
    </div>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'sucesso' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    unset($_SESSION['message']);	    
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>
<form class="form-search" id="formChamado" name="formChamado" method="post">
	<fieldset>
		<legend>Pesquisar Cliente</legend>
		<div class="row-fluid">
			<div class="span2">
				<label>Protocolo:</label> 
				<input type="text" class="span12" maxlength="14" style="width: 120px;">
			</div>
			<div class="span2">
				<label>CNPJ:&nbsp;&nbsp;&nbsp; </label> 
				<input type="text" class="span12" maxlength="14" style="width: 120px;">
			</div>
			<div class="span2">
				<label>CPF:&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; </label> 
				<input type="text" class="span12" maxlength="14" style="width: 120px;">
			</div>
			<div class="span2">
				<label>Name: </label> 
				<input type="text" class="span12"> 
			</div>
			<div class="span2">
				<label>Login: </label> 
				    <div class="input-append">
				    <input class="span12" id="appendedInputButtons" type="text">
				    <button class="btn btn-primary" type="submit">Pesquisar</button>
				    </div>
			</div>
		</div>
	</fieldset>
	<div><br><br></div>
	<fieldset>
		<legend>Chamado</legend>
		<div class="row-fluid">
			<div class="span3">
				<label>Provedor:</label> 
				<?php echo $this->provedor();?>
			</div>
			<div class="span3">
				<label>Categoria:</label> 
				<?php echo $this->categoria();?>
			</div>
			<div class="span3">
				<label>Status:&nbsp;</label> 
				<?php echo $this->status();?>
				<input type="hidden" name="data" id="data">
			</div>
			<div class="span3">
				<br><button class="btn btn-danger" type="button" id="abrirChamado">Abrir Chamado</button>
			</div>
		</div>
	</fieldset>
</form>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Protocolo</th>
			<th>Abertura</th>
			<th>Provedor</th>
			<th>Cliente</th>
			<th>Categoria</th>
			<th>Status</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $chamado) : 
	?>
		<tr>
			<td><?php echo $chamado['protocolo']?></td>
			<td><?php echo retornaDmy( $chamado['data'] )?></td>
			<td><?php echo $chamado['no_provedor']?></td>
			<td><?php echo $chamado['no_cliente']?></td>
			<td><?php echo $chamado['ds_categoria']?></td>
			<td align="center"><img alt="" src="<?=Zend_Registry::get('config')->caminho->componente;?>images/<?php echo $chamado['imagem']?>" title="<?php echo $chamado['ds_status']?>" /></td>
			<td>
				<a onclick="visualizar('<?php echo $chamado['id']?>')" href="#"><i class="icon-search"></i></a>
				<a onclick="editar('<?php echo $chamado['id']?>')" href="#"><i class="icon-edit"></i></a>
				<a onclick="$('#co_modal').val(<?php echo $chamado['id']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
