<script type="text/javascript">
$(function(){
	
	$("#tableRecentes").tablecloth({
		theme: "stats",
		bordered: true,
		condensed: true,
		striped: true,
		sortable: true,
		clean: true,
	});
	
});
</script>	
	
<table id="tableRecentes" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Protocolo</th>
			<th>Abertura</th>
			<th>Provedor</th>
			<th>Cliente</th>
			<th>Categoria</th>
			<th>Status</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginatorRecentes) ):
		foreach ( $this->paginatorRecentes as $recentes ) : 
	?>
		<tr>
			<td><?php echo $recentes['protocolo']?></td>
			<td><?php echo $recentes['data']?></td>
			<td><?php echo $recentes['no_provedor']?></td>
			<td><?php echo $recentes['no_cliente']?></td>
			<td><?php echo $recentes['ds_categoria']?></td>
			<td align="center"><img alt="" src="<?=Zend_Registry::get('config')->caminho->componente;?>images/<?php echo $recentes['imagem']?>" /></td>
			<td>
				<a onclick="editar(<?php echo $chamado['id']?>)" href="#"><i class="icon-edit"></i></a>
				<a onclick="$('#co_modal').val(<?php echo $recentes['id']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
