<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/financeiro/centrocusto/index.js" type="text/javascript"></script>
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: FINANCEIRO ::.
		<button style="float: right; margin-right: 15px;" href="" class="btn btn-primary" type="button" id="exibirInativos">Exibir Inativos</button>
		<button style="float: right; margin-right: 15px;" data-toggle="modal" href="#modalCadastroCentroCusto" class="btn btn-primary" type="button" id="novoRegistro">Novo Registro</button></h3>
	</div>
</div>
<div id="message_success" class="alert alert-success hide">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading"></h4>
</div>
<div id="message_error" class="alert alert-error hide">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading">Erro!</h4>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Centro de Custo</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
 						<tr>
							<th>Descrição</th>
							<th>Variável</th>
							<th>Opções</th>
						</tr>
					</thead>
					<tbody>
						<?php
							if( sizeof($this->arrCentroCusto) ):
							foreach ($this->arrCentroCusto as $centrocusto) :
						?>
						<tr>
							<td><?php echo $centrocusto['ds_centro_custo']?></td>
							<td><?php echo ($centrocusto['st_custo_variavel'] == 'S') ? 'Sim' : 'Não' ?></td>
							<td style="width: 150px;">
								<?php if($this->inativos ){?>
									<a class="btn btn-default" title="Ativar" href="#" onclick="ativar('<?php echo $centrocusto['co_centro_custo']?>')"><i class="glyphicon glyphicon-ok"></i></a>
								<?php }else{?>
									<a class="btn btn-default" title="Editar" href="#" onclick="editar('<?php echo $centrocusto['co_centro_custo']?>')"><i class="glyphicon glyphicon-edit"></i></a>
									<a class="btn btn-default" title="Excluir" href="#" onclick="deletar(<?php echo $centrocusto['co_centro_custo']?>)"><i class="glyphicon glyphicon-trash"></i></a>
								<?php }?>
							</td>
						</tr>
						<?php endforeach;?>
						<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->


<!-- Modal -->
<div class="modal" id="modalCadastroCentroCusto">
	<form name="frmCadastroCentroCusto" id="frmCadastroCentroCusto">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Centro de Custo</h4>
				</div>
				<div class="modal-body">
					<p>
					<div class="well bs-component">

						<form name="frmCadastroCrea" id="frmCadastroCrea" class="form-horizontal" action="" method="post">
							<div class="control-group">
								<label class="col-lg-3 control-label" for="co_pessoa_juridica">Descrição:</label>
								<div class="col-lg-9">
									<input type="hidden" name="co_centro_custo" id="co_centro_custo">
									<input class="input-xxlarge" required="required" type="text" name="ds_centro_custo" id="ds_centro_custo" size="50" value="" />
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="co_pessoa_juridica">Varável:</label>
								<div class="col-lg-9">
									<input type="radio" name="st_custo_variavel" id="st_custo_variavel_s" value="S" />Sim &nbsp;
									<input type="radio" name="st_custo_variavel" id="st_custo_variavel_n" value="N" />Não
								</div>
							</div>
							<div class="clear">&nbsp;</div>
						</form>
					</div>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnSalvar" class="btn btn-primary">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->