
<script type="text/javascript">
	var pesquisa = false;
	<?php if($this->pesquisa){ ?>
		var pesquisa = true;
	<?php } ?>
</script>

<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/financeiro/movimentacoes/boletos.js" type="text/javascript"></script>
<div class="navbar">
	<div class="navbar-inner">
		<button style="float: right" data-toggle="modal" href="#modalCadastro"  class="btn btn-primary" type="button" id="novoRegistro">Novo Boleto</button>
		<button style="float: right; margin-right: 10px;"  class="btn btn-primary" type="button" id="btnExcluirBoletos">Excluir Boletos</button>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Consulta</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<form name="frmPesquisar" id="frmPesquisar" method="post">
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="co_cliente">Cliente:</label>
						<div class="col-lg-10">
							<input type="hidden" name="nu_page" id="nu_page">
							<input type="hidden" name="st_consulta" id="st_consulta" value="<?php echo $this->st_consulta?>">
							<input type="hidden" name="st_gerar_pdf" id="st_gerar_pdf">
							<input type="hidden" name="st_gerar_boleto_cliente" id="st_gerar_boleto_cliente">
							<?php echo $this->cliente($this->co_pessoa_juridica)?>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="nu_documento">Número:</label>
						<div class="col-lg-10">
							<input type="text" name="nu_documento" id="nu_documento" value="<?php echo $this->nu_documento ?>">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="ds_nosso_numero">Nosso Número:</label>
						<div class="col-lg-10">
							<input type="text" name="ds_nosso_numero" id="ds_nosso_numero" value="<?php echo $this->ds_nosso_numero ?>">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="ds_fic_comp">Descrição:</label>
						<div class="col-lg-10">
							<input type="text" name="ds_fic_comp" id="ds_fic_comp" size="50" value="<?php echo $this->ds_fic_comp ?>">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Período Vencimento:</label>
						<div class="col-lg-1">
							De
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_inicio_vencimento" id="dt_inicio_vencimento" value="<?php echo $this->dt_inicio_vencimento ?>">
							<i title="Data Inicial" class="glyphicon glyphicon-calendar"></i>
						</div>
						<div class="col-lg-1">
							Até
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_final_vencimento" id="dt_final_vencimento" value="<?php echo $this->dt_final_vencimento ?>">
							<i title="Data Final" class="glyphicon glyphicon-calendar"></i>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Período Ocorrência:</label>
						<div class="col-lg-1">
							De
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_inicio_pagamento" id="dt_inicio_pagamento" value="<?php echo $this->dt_inicio_pagamento ?>">
							<i title="Data Inicial" class="glyphicon glyphicon-calendar"></i>
						</div>
						<div class="col-lg-1">
							Até
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_final_pagamento" id="dt_final_pagamento" value="<?php echo $this->dt_final_pagamento ?>">
							<i title="Data Final" class="glyphicon glyphicon-calendar"></i>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Pagamento:</label>
						<div class="col-lg-3">
							Aberto <input type="radio" name="st_pagamento" id="st_pagamento" value="1" <?php if($this->st_pagamento == 1){echo 'checked="checked"';} ?>>
							Quitado <input type="radio" name="st_pagamento" id="st_pagamento" value="2" <?php if($this->st_pagamento == 2){echo 'checked="checked"';} ?>>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<button style="float: right; margin: 5px;" class="btn btn-primary" type="submit" id="btnPesquisar">Pesquisar</button>
						<button style="float: right; margin: 5px;" class="btn btn-default" type="button" id="btnGerarPdf">Gerar PDF</button>
						<button style="float: right; margin: 5px;" class="btn btn-default" type="button" id="btnGerarCliente">Gerar PDF Boletos</button>
						<button style="float: right; margin: 5px;" class="btn btn-default" type="button" id="btnLimpar">Limpar</button>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
				</form>

			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->

<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Boletos</h3>
				<div class="clear">&nbsp;</div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<div class="info-box bg-green">
						<span class="info-box-icon">
							<span class="info-box-text"><span style="cursor: pointer" id="st_pagos">Pagos</span></span>
						</span>

						<div class="info-box-content">
							<span class="info-box-number">R$ <?php echo formatValShow($this->pagos, 2) ?></span>
							<div class="progress">
								<?php $pagosPercent = $this->pagos * 100 / $this->total ?>
								<div style="width: <?php echo number_format($pagosPercent, 2, '.', ''); ?>%"
									 class="progress-bar"></div>
							</div>
							<span class="progress-description">
								<span class="progress-description"><?php echo number_format($pagosPercent, 2, '.', ''); ?>%</span>
								<span class="progress-description"><?php echo $this->cPagos; ?> Boletos</span>
						  	</span>
						</div>
						<!-- /.info-box-content -->
					</div>
				</div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<div class="info-box bg-red">
						<span class="info-box-icon">
							<span class="info-box-text"><span style="cursor: pointer" id="st_vencidos">Abertos</span></span>
						</span>

						<div class="info-box-content">
							<span class="info-box-number">R$ <?php echo formatValShow($this->abertos, 2) ?></span>
							<div class="progress">
								<?php $abertosPercent = $this->abertos * 100 / $this->total ?>
								<div style="width: <?php echo number_format($vencidosPercent, 2, '.', ''); ?>%"
									 class="progress-bar"></div>
							</div>
							<span class="progress-description">
								<span class="progress-description"><?php echo number_format($abertosPercent, 2, '.', ''); ?>%</span>
								<span class="progress-description"><?php echo $this->cAbertos; ?> Boletos</span>
						  	</span>
						</div>
						<!-- /.info-box-content -->
					</div>
				</div>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Número</th>
							<th>Cliente</th>
							<th>Nosso Número</th>
							<th>Valor</th>
							<th>Dt Vencimento</th>
							<th>Dt Pagamento</th>
							<th>Opções</th>
						</tr>
					</thead>
					<tbody>
					<?php
					if( count($this->paginator ) ):
						foreach ($this->paginator as $boleto) :
					?>
						<tr>
							<td><?php echo $boleto['nu_documento']?></td>
							<td><?php echo limitarTexto($boleto['no_razao_social'], 50)?></td>
							<td><?php echo $boleto['nu_nosso_numero']?></td>
							<td><?php echo 'R$ '.moeda( $boleto['ds_valor'] )?></td>
							<td>
								<?php
									if(  $boleto['dt_vencimento'] < Zend_Date::now()->toString("Y-MM-d") && empty($boleto['dt_ocorrencia']) )	:
										echo '<span title="Vencido" class="btn-danger badge">'.retornaDmy( $boleto['dt_vencimento'] ).'</span>';
									elseif( $boleto['dt_vencimento'] >= Zend_Date::now()->toString("Y-MM-d") && $boleto['dt_vencimento'] <= Zend_Date::now()->addDay(2)->toString("Y-MM-d") && empty($boleto['dt_ocorrencia']) ):
										echo '<span title="Vencendo" class="btn-warning badge">'.retornaDmy( $boleto['dt_vencimento'] ).'</span>';
									else:
										echo retornaDmy( $boleto['dt_vencimento'] );
									endif;
								?>
							</td>
							<td><?php echo retornaDmy( $boleto['dt_ocorrencia'] ) ?></td>
							<td style="width: 150px;">
								<a class="btn btn-default" style="cursor: pointer;" onclick="gerarBoleto('<?php echo $boleto['co_boleto']?>')"><i title="Gerar Boleto" class="glyphicon glyphicon-barcode"></i></a>

								<?php if( empty($boleto['dt_ocorrencia']) ):?>
									<a class="btn btn-default" id="quitarboleto-<?php echo $boleto['co_boleto']?>" style="cursor: pointer;" onclick="quitarBoleto('<?php echo $boleto['co_boleto']?>')"><i title="Quitar Parcela" class="glyphicon glyphicon-thumbs-up"></i></a>
								<?php endif;?>
								<?php
								if(  $boleto['dt_vencimento'] < Zend_Date::now()->toString("Y-MM-d") && empty($boleto['dt_ocorrencia']) )	: ?>
									<a class="btn btn-default" style="cursor: pointer;" onclick="enviarAdvogado('<?php echo $boleto['co_boleto']?>')"><i title="Enviar para Advogado" class="glyphicon glyphicon-user"></i></a>
								<?php endif;?>
							</td>
						</tr>
					<?php endforeach;?>
					<?php else:?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
<div class="col-md-4 col-sm-6 col-xs-12">
	<div class="info-box bg-grey">
		<span class="info-box-icon"><span class="info-box-text">Total</span></span>

		<div class="info-box-content">
			<br>
			<span class="info-box-number">R$ <?php echo formatValShow($this->total, 2) ?></span>
			<span class="progress-description">
				<span class="progress-description"><?php echo $this->cTotal; ?> Boletos</span>
			</span>
		</div>
		<!-- /.info-box-content -->
	</div>
</div>

<?php
	if(!$this->pesquisa){
		echo $this->paginator;
	}
?>
<!-- Modal -->
<div class="modal" id="modalCadastro">
	<form name="frmCadBoleto" id="frmCadBoleto">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<i aria-hidden="true">&times;</i>
					</button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Boleto</h4>
				</div>
				<div class="modal-body">
					<p>
					<div class="well bs-component">
						<div class="form-group">
							<label class="col-lg-3 control-label" for="no_servico">Nome:</label>
							<div class="col-lg-9">
								<?php echo $this->clienteboleto(null, 'class="form-control col-xs-6"') ?>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="form-group">
							<label class="col-lg-3 control-label" for="no_servico">Vencimento:</label>
							<div class="col-lg-9">
								<div class="input-group col-xs-6">
									<span class="input-group-addon"><i title="Data de vencimento" class="glyphicon glyphicon-calendar"></i></span>
									<input type="text" required="required" class="form-control" name="dt_vencimento" id="dt_vencimento" value="">
								</div>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="form-group">
							<label class="col-lg-3 control-label" for="no_servico">Qtd Parcelas:</label>
							<div class="col-lg-9">
								<div class="input-group col-xs-6">
									<select name="nu_qtd_parcelas" id="nu_qtd_parcelas" class="form-control col-xs-2">
										<?php for($i=1;$i<=48;$i++){?>
										<option><?php echo $i;?></option>
										<?php }?>
									</select>
								</div>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="form-group">
							<label class="col-lg-3 control-label" for="sg_servico">Valor:</label>
							<div class="col-lg-9">
									<input type="text" required="required" class="form-control" name="ds_valor" id="ds_valor" value="">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="form-group">
							<label class="col-lg-3 control-label" for="nu_documento">Nro. Documento:</label>
							<div class="col-lg-9">
								<input type="text" required="required" class="form-control" name="nu_documento" id="nu_documento" value="">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-3 control-label" for="inputNome">Descrição:</label>
							<div class="col-lg-9">
								<textarea id="ds_modelo" required="required" name="ds_fic_comp" rows="3" class="form-control"></textarea>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
					</div>
					</p>
					<div class="clear">&nbsp;</div>

				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnSalvar" class="btn btn-primary">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->