<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: DESPESAS VENCIDAS ::.
			<button style="float: right" data-toggle="modal" href="#modalCadastro" class="btn btn-warning" onclick="location.href='<?php echo $this->baseUrl()?>/financeiro/movimentacoes/index'" type="button" id="novoRegistro">Voltar</button> &nbsp;&nbsp;
		</h3>
	</div>
	
</div>
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Código</th>
			<th>Descrição</th>
			<th>Valor</th>
			<th>Vencimento</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->dPaginator) ):
		foreach ($this->dPaginator as $despesa) : 
	?>
		<tr>
			<td><?php echo $despesa['co_movimentacao']?></td>
			<td><?php echo $despesa['ds_movimentacao'] ?></td>
			<td><?php echo 'R$ '.moeda( $despesa['ds_valor'] )?></td>
			<td><?php echo retornaDmy( $despesa['dt_vencimento'] ) ?></td>
				<td>
				<a href="#" onclick="editarDespesa('<?php echo $despesa['co_movimentacao']?>')"><i class="icon-edit"></i></a>
				<a href="#" onclick="$('#co_modal').val(<?php echo $despesa['co_movimentacao']?>);$('#confirm-dialog').modal('show');"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->dPaginator; ?>