<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/financeiro/movimentacoes/despesas.js" type="text/javascript"></script>
<div class="navbar">
	<div class="navbar-inner">
		<button style="float: right" data-toggle="modal" href="#modalCadastroDespesas" class="btn btn-primary" type="button" id="novoRegistroDespesa">Nova Despesa</button> &nbsp;&nbsp;
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Consulta</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<form name="frmPesquisar" id="frmPesquisar" method="post">
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="co_centro_custo">Centro de Custo:</label>
						<div class="col-lg-10">
							<input type="hidden" name="nu_page" id="nu_page">
							<input type="hidden" name="st_consulta" id="st_consulta">
							<input type="hidden" name="st_gerar_pdf" id="st_gerar_pdf">
							<?php echo $this->centrocusto($this->co_centro_custo)?>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="ds_despesa">Descrição:</label>
						<div class="col-lg-6">
							<input type="text" class="form-control" name="ds_despesa" id="ds_despesa" size="50" value="<?php echo $this->ds_despesa ?>">
						</div>
						<div class="clear">&nbsp;</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Período Vencimento:</label>
						<div class="col-lg-1">
							De
						</div>
						<div class="col-lg-3">
							<div class="input-group">
								<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" title="Data de início de vencimento"></i></span>
								<input type="text" value="<?php echo $this->dt_inicio_vencimento ?>" id="dt_inicio_vencimento" name="dt_inicio_vencimento" class="form-control">
							</div>
						</div>
						<div class="col-lg-1">
							Até
						</div>
						<div class="col-lg-3">
							<div class="input-group">
								<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" title="Data final de vencimento"></i></span>
								<input type="text" value="<?php echo $this->dt_final_vencimento ?>" id="dt_final_vencimento" name="dt_final_vencimento" class="form-control">
							</div>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Período Pagamento:</label>
						<div class="col-lg-1">
							De
						</div>
						<div class="col-lg-3">
							<div class="input-group">
								<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" title="Data de início de pagamento"></i></span>
								<input type="text" value="<?php echo $this->dt_inicio_pagamento ?>" id="dt_inicio_pagamento" name="dt_inicio_pagamento" class="form-control">
							</div>
						</div>
						<div class="col-lg-1">
							Até
						</div>
						<div class="col-lg-3">
							<div class="input-group">
								<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" title="Data final de pagamento"></i></span>
								<input type="text" value="<?php echo $this->dt_final_pagamento ?>" id="dt_final_pagamento" name="dt_final_pagamento" class="form-control">
							</div>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Pagamento:</label>
						<div class="col-lg-3">
							Aberto <input type="radio" name="st_pagamento" id="st_pagamento" value="1" <?php if($this->st_pagamento == 1){echo 'checked="checked"';} ?>>
							Quitado <input type="radio" name="st_pagamento" id="st_pagamento" value="2" <?php if($this->st_pagamento == 2){echo 'checked="checked"';} ?>>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<button style="float: right; margin: 5px;" class="btn btn-primary" type="submit" id="btnPesquisar">Pesquisar</button>
						<button style="float: right; margin: 5px;" class="btn btn-default" type="button" id="btnGerarPdf">Gerar PDF</button>
						<button style="float: right; margin: 5px;" class="btn btn-default" type="button" id="btnLimpar">Limpar</button>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
				</form>

			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Despesas</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<div class="col-md-3 col-sm-6 col-xs-12">
					<div class="info-box bg-green">
						<span class="info-box-icon">
							<span class="info-box-text"><span style="cursor: pointer" id="st_pagos">Pagos</span></span>
						</span>

						<div class="info-box-content">
							<span class="info-box-number">R$ <?php echo formatValShow($this->pagos, 2) ?></span>
							<div class="progress">
								<?php $pagosPercent = $this->pagos * 100 / $this->total ?>
								<div style="width: <?php echo number_format($pagosPercent, 2, '.', ''); ?>%"
									 class="progress-bar"></div>
							</div>
							<span class="progress-description">
								<span class="progress-description"><?php echo number_format($pagosPercent, 2, '.', ''); ?>%</span>
								<span class="progress-description"><?php echo $this->cPagos; ?> Despesas</span>
						  	</span>
						</div>
						<!-- /.info-box-content -->
					</div>
				</div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<div class="info-box bg-yellow">
						<span class="info-box-icon">
							<span class="info-box-text"><span style="cursor: pointer" id="st_vencendo">Vencendo</span></span>
						</span>

						<div class="info-box-content">
							<span class="info-box-number">R$ <?php echo formatValShow($this->vencendo, 2) ?></span>
							<div class="progress">
								<?php $vencendoPercent = $this->vencendo * 100 / $this->total ?>
								<div style="width: <?php echo number_format($vencendoPercent, 2, '.', ''); ?>%"
									 class="progress-bar"></div>
							</div>
							<span class="progress-description">
								<span class="progress-description"><?php echo number_format($vencendoPercent, 2, '.', ''); ?>%</span>
								<span class="progress-description"><?php echo $this->cVencendo; ?> Despesas</span>
						  	</span>
						</div>
						<!-- /.info-box-content -->
					</div>
				</div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<div class="info-box bg-red">
						<span class="info-box-icon">
							<span class="info-box-text"><span style="cursor: pointer" id="st_vencidos">Vencidos</span></span>
						</span>

						<div class="info-box-content">
							<span class="info-box-number">R$ <?php echo formatValShow($this->vencidos, 2) ?></span>
							<div class="progress">
								<?php $vencidosPercent = $this->vencidos * 100 / $this->total ?>
								<div style="width: <?php echo number_format($vencidosPercent, 2, '.', ''); ?>%"
									 class="progress-bar"></div>
							</div>
							<span class="progress-description">
								<span class="progress-description"><?php echo number_format($vencidosPercent, 2, '.', ''); ?>%</span>
								<span class="progress-description"><?php echo $this->cVencidos; ?> Despesas</span>
						  	</span>
						</div>
						<!-- /.info-box-content -->
					</div>
				</div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<div class="info-box bg-blue">
						<span class="info-box-icon">
							<span class="info-box-text"><span style="cursor: pointer" id="st_avencer">A Vencer</span></span>
						</span>

						<div class="info-box-content">
							<span class="info-box-number">R$ <?php echo formatValShow($this->vencer, 2) ?></span>
							<div class="progress">
								<?php $vencerPercent = $this->vencer * 100 / $this->total ?>
								<div style="width: <?php echo number_format($vencerPercent, 2, '.', ''); ?>%"
									 class="progress-bar"></div>
							</div>
							<span class="progress-description">
								<span class="progress-description"><?php echo number_format($vencerPercent, 2, '.', ''); ?>%</span>
								<span class="progress-description"><?php echo $this->cVencer; ?> Despesas</span>
						  	</span>
						</div>
						<!-- /.info-box-content -->
					</div>
				</div>
				<div class="clear">&nbsp;</div>
				<div class="clear">&nbsp;</div>
				<table id="tableDespesas" class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Descrição</th>
							<th>Valor</th>
							<th>Vencimento</th>
							<th>Obervação</th>
							<th>Opções</th>
						</tr>
					</thead>
					<tbody>
					<?php
					if( sizeof($this->paginator) ):
						foreach ($this->paginator as $despesa) :
					?>
						<tr>
							<td><?php echo $despesa['ds_despesa'] ?></td>
							<td><?php echo 'R$ '.moeda( $despesa['ds_valor'] )?></td>
							<td>
								<?php
								if( $despesa['dt_quitacao'] ):
									echo '<span title="Pago" class="btn-success badge pago">'.retornaDmy( $despesa['dt_vencimento'] ).'</span>';
								else:
									if(  $despesa['dt_vencimento'] < Zend_Date::now()->toString("Y-MM-d") && empty($despesa['dt_pagamento']) )	:
										echo '<span title="Vencido" class="btn-danger badge">'.retornaDmy( $despesa['dt_vencimento'] ).'</span>';
									elseif( $despesa['dt_vencimento'] >= Zend_Date::now()->toString("Y-MM-d") && $despesa['dt_vencimento'] <= Zend_Date::now()->addDay(2)->toString("Y-MM-d") && empty($despesa['dt_pagamento']) ):
										echo '<span title="Vencendo" class="btn-info badge">'.retornaDmy( $despesa['dt_vencimento'] ).'</span>';
									else:
										echo retornaDmy($despesa['dt_vencimento']);
									endif;
								endif;
								?>
							</td>
							<td><?php echo $despesa['ds_observacao'] ?></td>
							<td style="width: 150px;">
								<a class="btn btn-default" href="#" onclick="editarDespesa('<?php echo $despesa['co_despesa']?>')"><i class="glyphicon glyphicon-edit"></i></a>
								<a class="btn btn-default" href="#" onclick="$('#co_modal').val(<?php echo $despesa['co_despesa']?>);$('#confirm-dialog').modal('show');"><i class="glyphicon glyphicon-trash"></i></a>
								<?php if( empty($despesa['dt_pagamento'])):?>
									<a class="btn btn-default" style="cursor: pointer;" onclick="quitar('<?php echo $despesa['co_despesa']?>')"><i title="Quitar Despesa" class="glyphicon glyphicon-thumbs-up"></i></a>
								<?php else:?>
									<a class="btn btn-default"><i title="Despesa paga" class="glyphicon glyphicon-ok"></i></a>
								<?php endif;?>
							</td>
						</tr>
					<?php endforeach;?>
					<?php else:?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
<div class="col-md-4 col-sm-6 col-xs-12">
	<div class="info-box bg-grey">
		<span class="info-box-icon"><span class="info-box-text">Total</span></span>

		<div class="info-box-content">
			<br>
			<span class="info-box-number">R$ <?php echo formatValShow($this->total, 2) ?></span>
			<span class="progress-description">
				<span class="progress-description"><?php echo $this->cTotal; ?> Boletos</span>
			</span>
		</div>
		<!-- /.info-box-content -->
	</div>
</div>
<?php
if(!$this->pesquisa){
	echo $this->paginator;
}
?>
<!-- Modal -->
<div class="modal" id="modalCadastroDespesas">
	<form name="frmCadDespesa" id="frmCadDespesa">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Despesa</h4>
				</div>
				<div class="modal-body">
					<div class="well bs-component">
						<div class="control-group">
							<label class="col-lg-4 control-label" for="inputNome">Duplicar: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<input type="checkbox" name="st_despesa_duplica" id="st_despesa_duplica">
							</div>
						</div>
						<div class="clear qtd_despesa" style="display: none">&nbsp;</div>
						<div class="control-group qtd_despesa" style="display: none">
							<label class="col-lg-4 control-label" for="inputNome">Quantidade: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<select name="nu_qtd_despesa" id="nu_qtd_despesa">
									<option value="0">Selecione...</option>
									<?php for($i=0;$i<21;$i++){?>
									<option value="<?php echo $i?>"><?php echo $i?></option>
									<?php }?>
								</select>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="inputNome">Conta de Origem: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<input type="hidden" name="co_despesa" id="co_despesa">
								<?php echo $this->banco()?>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="co_centro_custo">Centro de Custo: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<?php echo $this->centrocusto(null, 'required="required"')?>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="ds_documento">Documento: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<input type="text" name="ds_documento" id="ds_documento" class="form-control" required="required">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="control-label" for="inputNome">Despesa refere à:</label>
							<div class="controls">
								<textarea class="form-control" name="ds_despesa" id="ds_despesa"></textarea>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="ds_fornecedor_despesa">Fornecedor: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<input class="form-control" type="text" required name="ds_fornecedor" id="ds_fornecedor_despesa">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="ds_valor_despesa">Valor: <span style="color:red">*</span></label>
							<div class="col-lg-8">
								<input class="form-control" type="text" required name="ds_valor" id="ds_valor">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="st_movimentacao">Situação: <span style="color:red">*</span></label>
							<div class="col-lg-8 controls">
								<input type="radio" name="st_despesa" id="st_despesa_paga" value="1"> Pago
								<input type="radio" name="st_despesa" id="st_movimentacao_despesa_pagar" value="0"> À Pagar
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="dt_pagamento_despesa">Data Pagamento: <span style="color:red">*</span></label>
							<div class="col-lg-8 controls">
								<div class="input-group col-xs-6">
									<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" title="Data de vencimento"></i></span>
									<input type="text" value="" id="dt_pagamento" name="dt_pagamento_despesa" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-4 control-label" for="dt_vencimento_despesa">Data Vencimento: <span style="color:red">*</span></label>
							<div class="col-lg-8 controls">
								<div class="input-group col-xs-6">
									<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" title="Data de vencimento"></i></span>
									<input type="text" value="" id="dt_vencimento" name="dt_vencimento" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="control-label" for="inputNome">Observações:</label>
							<div class="controls">
								<textarea class="form-control" name="ds_observacao" id="ds_observacao_despesa"></textarea>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" class="btn btn-primary" id="btnSalvar">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->
<!-- modal -->
<div class="modal" id="modalQuitarDespesa">
	<form name="frmQuitarDespesa" id="frmQuitarDespesa">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Despesa</h4>
				</div>
				<div class="modal-body">
					<p>
					<div class="control-group">
						<div class="col-lg-12">
							Deseja quitar esta despesa?
							<input type="hidden" name="co_movimentacao" id="co_movimentacao" value="D">
						</div>
					</div>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Não</button>
					<button type="submit" class="btn btn-primary" id="btnSalvarQuitacao">Sim</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form><!-- /.form -->
</div><!-- /.modal -->