<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/financeiro/movimentacoes/excluir-boletos.js" type="text/javascript"></script>
<?php
if($_SESSION['message']['msg'] == 'success'):?>
<div id="message_success" class="alert alert-success">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading"><?php echo $_SESSION['message']['message'];?></h4>
</div>
<?php elseif($_SESSION['message']['msg'] == 'error'):?>
<div id="message_error" class="alert alert-error">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading"><?php echo $_SESSION['message']['message'];?></h4>
</div>
<?php endif;?>

<script type="text/javascript">
	<?php if( $_SESSION['message']['msg'] == 'success' ) : unset($_SESSION['message'])?>
	$('#message_success').show('slide').delay(8000).hide('slide');
	<?php elseif( $this->msg == 'erro' ) :?>
	$('#message_error').show('slide').delay(8000).hide('slide');
	<?php
	endif;
	?>
	var data = '<?php echo $this->data;?>';
</script>

<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Excluir Boletos</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<form name="frmPesquisar" id="frmPesquisar" method="post">
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="co_cliente">Cliente:</label>
						<div class="col-lg-10">
							<input type="hidden" name="nu_page" id="nu_page">
							<input type="hidden" name="st_consulta" id="st_consulta" value="<?php echo $this->st_consulta?>">
							<input type="hidden" name="st_listar" id="st_listar" value="true">
							<?php echo $this->cliente($this->co_pessoa_juridica)?>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_inicio_vencimento">Período Vencimento:</label>
						<div class="col-lg-1">
							De
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_inicio_vencimento" id="dt_inicio_vencimento" value="<?php echo $this->dt_inicio_vencimento ?>">
							<i title="Data Inicial" class="glyphicon glyphicon-calendar"></i>
						</div>
						<div class="col-lg-1">
							Até
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_final_vencimento" id="dt_final_vencimento" value="<?php echo $this->dt_final_vencimento ?>">
							<i title="Data Final" class="glyphicon glyphicon-calendar"></i>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Período Ocorrência:</label>
						<div class="col-lg-1">
							De
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_inicio_pagamento" id="dt_inicio_pagamento" value="<?php echo $this->dt_inicio_pagamento ?>">
							<i title="Data Inicial" class="glyphicon glyphicon-calendar"></i>
						</div>
						<div class="col-lg-1">
							Até
						</div>
						<div class="col-lg-3">
							<input type="text" name="dt_final_pagamento" id="dt_final_pagamento" value="<?php echo $this->dt_final_pagamento ?>">
							<i title="Data Final" class="glyphicon glyphicon-calendar"></i>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<label class="col-lg-2 control-label" for="dt_final">Pagamento:</label>
						<div class="col-lg-5">
							<input type="radio" name="st_consulta" id="st_consulta" value="pagos" <?php if($this->st_pagamento == 1){echo 'checked="checked"';} ?>>
							Pagos
							<input type="radio" name="st_consulta" id="st_consulta" value="abertos" <?php if($this->st_pagamento == 2){echo 'checked="checked"';} ?>>
							Abertos
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="control-group">
						<button style="float: right; margin: 5px;" class="btn btn-primary" type="submit" id="btnListar">Listar</button>
						<button style="float: right; margin: 5px;" class="btn btn-default" type="button" id="btnLimpar">Limpar</button>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="clear">&nbsp;</div>
				</form>

			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->

<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Lista</h3>
				<button style="float: right; margin-right: 10px;" data-toggle="modal" href="#modalExclusao" class="btn btn-primary" type="button" id="btnExcluirBoletos">Excluir Boleto(s)</button>
				<div class="clear">&nbsp;</div>

			</div><!-- /.box-header -->
			
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
					<tr>
						<th><input type="checkbox" id="selecionarTodos"></th>
						<th>Número</th>
						<th>Cliente</th>
						<th>Nosso Número</th>
						<th>Valor</th>
						<th>Dt Vencimento</th>
						<th>Dt Pagamento</th>
					</tr>
					</thead>
					<tbody>
					<?php
					if( count($this->paginator ) ):
						foreach ($this->paginator as $boleto) :
							?>
							<tr>
								<td><input type="checkbox" value="<?php echo $boleto['co_boleto']?>" email="<?php echo $boleto['ds_email']?>" checked="checked"></td>
								<td><?php echo $boleto['nu_documento']?></td>
								<td><?php echo limitarTexto($boleto['no_razao_social'], 50)?></td>
								<td><?php echo $boleto['nu_nosso_numero']?></td>
								<td><?php echo 'R$ '.moeda( $boleto['ds_valor'] )?></td>
								<td>
									<?php
									if(  $boleto['dt_vencimento'] < Zend_Date::now()->toString("Y-MM-d") && empty($boleto['dt_ocorrencia']) )	:
										echo '<span title="Vencido" class="btn-danger badge">'.retornaDmy( $boleto['dt_vencimento'] ).'</span>';
									elseif( $boleto['dt_vencimento'] >= Zend_Date::now()->toString("Y-MM-d") && $boleto['dt_vencimento'] <= Zend_Date::now()->addDay(2)->toString("Y-MM-d") && empty($boleto['dt_ocorrencia']) ):
										echo '<span title="Vencendo" class="btn-warning badge">'.retornaDmy( $boleto['dt_vencimento'] ).'</span>';
									else:
										echo retornaDmy( $boleto['dt_vencimento'] );
									endif;
									?>
								</td>
								<td><?php echo retornaDmy( $boleto['dt_ocorrencia'] ) ?></td>
							</tr>
						<?php endforeach;?>
					<?php else:?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->


<!-- Modal -->
<div class="modal" id="modalExclusao">
	<form name="frmConsultaEmail" id="frmConsultaEmail" method="post" action="<?php echo $this->baseUrl()?>/financeiro/email/enviar-email">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><i
							aria-hidden="true">&times;</i></button>
					<h4 class="modal-title" id="tituloModalExistente">Enviar E-mail</h4>
				</div>
				<div class="modal-body">
					<p>
					<div class="well bs-component">

						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-3 control-label" for="inputNome">Justificativa:</label>
							<div class="col-lg-12">
								<input type="hidden" name="co_boleto[]" id="co_boleto" value="">
								<textarea id="ds_justificativa_exclusao" name="ds_justificativa_exclusao" rows="3" class="form-control"></textarea>
							</div>
							<div class="clear">&nbsp;</div>
						</div>
						<div class="clear">&nbsp;</div>
					</div>
					</p>
					<div class="clear">&nbsp;</div>

				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="button" id="btnExcluir" class="btn btn-primary">Confirmar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->