<div class="navbar">
	<div class="navbar-inner">
		<button style="float: right" data-toggle="modal" href="#modalCadastroReceitas" class="btn btn-primary" type="button" id="novoRegistro">Nova Receita</button> &nbsp;&nbsp;
	</div>
</div>
<table id="tableReceitas" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Código</th>
			<th>Descrição</th>
			<th>Valor</th>
			<th>Vencimento</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->arrReceitas) ):
		foreach ($this->arrReceitas as $receita) :
	?>
		<tr>
			<td><?php echo $receita['co_movimentacao']?></td>
			<td><?php echo $receita['ds_movimentacao'] ?></td>
			<td><?php echo 'R$ '.moeda( $receita['ds_valor'] )?></td>
			<td>
				<?php 
					if(  $receita['dt_vencimento'] < Zend_Date::now()->toString("Y-MM-d") && $receita['st_quitacao'] != 'S' )	:
						echo '<span class="badge badge-important">'.retornaDmy( $receita['dt_vencimento'] ).'</span>';
					elseif( $receita['dt_vencimento'] == Zend_Date::now()->toString("Y-MM-d") && $receita['st_quitacao'] == 'S' ):
						echo '<span class="badge badge-info">'.retornaDmy( $receita['dt_vencimento'] ).'</span>';
					elseif( $receita['st_quitacao'] == 'S' ):
						echo '<span class="label label-success">'.retornaDmy( $receita['dt_vencimento'] ).'</span>';
					else:
						echo retornaDmy( $receita['dt_vencimento'] );
					endif; 					
				?>
			</td>
				<td>
				<a href="#" onclick="editarreceita('<?php echo $receita['co_movimentacao']?>')"><i class="glyphicon glyphicon-edit"></i></a>
				<a href="#" onclick="$('#co_modal').val(<?php echo $receita['co_movimentacao']?>);$('#confirm-dialog').modal('show');"><i class="glyphicon glyphicon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;?>
	<?php endif;?>
	</tbody>
</table>
<script>
	$('#tableReceitas').dataTable( {
		"bSort": false,
		"oLanguage": {
			"oPaginate": {
				"sLast": "Ultima",
				"sNext": "Próxima",
				"sPrevious": "Anterior",
				"sEmptyTable": "Nenhum registro encontrado!",
				"sInfo": "Got a total of _TOTAL_ entries to show (_START_ to _END_)"
			}
		}
	} );
</script>