<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/financeiro/movimentacoes/index.js" type="text/javascript"></script>

<style>

section {
    padding: 5% 0;
}

.alizarin {
    background: #e74c3c;
}

.amethyst {
    background: #9b59b6;
}

.emerald {
    background: #2ecc71;
}

.midnight-blue {
    background: #2c3e50;
}

.peter-river {
    background: #3498db;
}

.dl {
    background: #f0f0f0;
    padding: 30px 0;
    border-radius: 20px;
    position: relative;
}

.dl:before {
    content: " ";
    height: 20px;
    width: 20px;
    background: #ddd;
    border-radius: 20px;
    position: absolute;
    left: 50%;
    top: 20px;
    margin-left: -10px;
}

.dl .brand {
    text-transform: uppercase;
    letter-spacing: 3px;
    padding: 10px 15px;
    margin-top: 10px;
    text-align: center;
    min-height: 50px;
}

.dl .discount {
    min-height: 50px;
    position: relative;
    font-size: 30px;
    line-height: 80px;
    text-align: center;
    font-weight: bold;

    padding: 20px 15px 0;
    color: #FFF;
}

.dl .discount:after {
    content: " ";

    border-right: 20px solid transparent;
    border-left: 20px solid transparent;
    position: absolute;
    bottom: -20px;
    left: 20%;
}

.dl .discount.alizarin:after {
    border-top: 20px solid #e74c3c;
}

.dl .discount.peter-river:after {
    border-top: 20px solid #3498db;
}

.dl .discount.emerald:after {
    border-top: 20px solid #2ecc71;
}

.dl .discount.amethyst:after {
    border-top: 20px solid #9b59b6;
}

.dl .discount .type {
    font-size: 20px;
    letter-spacing: 1px;
    text-transform: uppercase;
    margin-top: -30px;
}

.dl .descr {
    color: #999;
    margin-top: 10px;
    padding: 20px 15px;
}

.dl .ends {
    padding: 0 15px;
    color: #f1c40f;
    margin-bottom: 10px;
}

.dl .coupon {
    min-height: 50px;
    text-align: center;

    text-transform: uppercase;
    font-weight: bold;
    font-size: 18px;
    padding: 20px 15px;
}

.dl .coupon a.open-code {
    color: #16a085;
}

.dl .coupon .code {
    letter-spacing: 1px;
    border-radius: 4px;
    margin-top: 10px;
    padding: 10px 15px;
    color: #f1c40f;
    background: #f0f0f0;
}


.d2 {
	background: #f0f0f0;
	padding: 30px 0;
	border-radius: 20px;
	position: relative;
}

.d2:before {
	content: " ";
	height: 20px;
	width: 20px;
	background: #ddd;
	border-radius: 20px;
	position: absolute;
	left: 50%;
	top: 20px;
	margin-left: -10px;
}

.d2 .brand {
	text-transform: uppercase;
	letter-spacing: 3px;
	padding: 10px 15px;
	margin-top: 10px;
	text-align: center;
	min-height: 50px;
}

.d2 .discount {
	min-height: 50px;
	position: relative;
	font-size: 30px;
	line-height: 80px;
	text-align: center;
	font-weight: bold;

	padding: 20px 15px 0;
	color: #f1c40f;
}

.d2 .discount:after {
	content: " ";

	border-right: 20px solid transparent;
	border-left: 20px solid transparent;
	position: absolute;
	bottom: -20px;
	left: 20%;
}

.d2 .discount.alizarin:after {
	border-top: 20px solid #e74c3c;
}

.d2 .discount.peter-river:after {
	border-top: 20px solid #3498db;
}

.d2 .discount.emerald:after {
	border-top: 20px solid #2ecc71;
}

.d2 .discount.amethyst:after {
	border-top: 20px solid #9b59b6;
}

.d2 .discount .type {
	font-size: 20px;
	letter-spacing: 1px;
	text-transform: uppercase;
	margin-top: -30px;
}

.d2 .descr {
	color: #999;
	margin-top: 10px;
	padding: 20px 15px;
}

.d2 .ends {
	padding: 0 15px;
	color: #f1c40f;
	margin-bottom: 10px;
}

.d2 .coupon {
	min-height: 50px;
	text-align: center;

	text-transform: uppercase;
	font-weight: bold;
	font-size: 18px;
	padding: 20px 15px;
}

.d2 .coupon a.open-code {
	color: #16a085;
}

.d2 .coupon .code {
	letter-spacing: 1px;
	border-radius: 4px;
	margin-top: 10px;
	padding: 10px 15px;
	color: #f1c40f;
	background: #f0f0f0;
}


.dropdown-menu{
	float: none;
}
.panel {
  padding: 15px;
  margin-bottom: 20px;
  background-color: #ffffff;
  border: 1px solid #dddddd;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
}

.panel-heading {
  padding: 10px 15px;
  margin: -15px -15px 15px;
  font-size: 17.5px;
  font-weight: 500;
  background-color: #f5f5f5;
  border-bottom: 1px solid #dddddd;
  border-top-right-radius: 3px;
  border-top-left-radius: 3px;
}

.panel-footer {
  padding: 10px 15px;
  margin: 15px -15px -15px;
  background-color: #f5f5f5;
  border-top: 1px solid #dddddd;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}

.panel-primary {
  border-color: #428bca;
}

.panel-primary .panel-heading {
  color: #ffffff;
  background-color: #428bca;
  border-color: #428bca;
}

.panel-success {
  border-color: #d6e9c6;
}

.panel-success .panel-heading {
  color: #468847;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}

.panel-warning {
  border-color: #fbeed5;
}

.panel-warning .panel-heading {
  color: #c09853;
  background-color: #fcf8e3;
  border-color: #fbeed5;
}

.panel-danger {
  border-color: #eed3d7;
}

.panel-danger .panel-heading {
  color: #b94a48;
  background-color: #f2dede;
  border-color: #eed3d7;
}

.panel-info {
  border-color: #bce8f1;
}

.panel-info .panel-heading {
  color: #3a87ad;
  background-color: #d9edf7;
  border-color: #bce8f1;
}
</style>
<div id="message_success" class="alert alert-success hide">
<a class="close" data-dismiss="alert">×</a>
<h4 class="alert-heading"></h4>
</div>

<div id="message_error" class="alert alert-error hide">
<a class="close" data-dismiss="alert">×</a>
<h4 class="alert-heading">Erro!</h4>
</div>

<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: FINANCEIRO ::.</h3>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">MOVIMENTAÇÕES</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<div id="conteudo">
					<?php if( $this->vencidas > 0 ):?>
						<div class="alert alert-error">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<h4>Despesas Vencidas!</h4>
							Exite(m) <span class="badge badge-warning"><?php echo $this->vencidas?></span> Despesas vencidas! <span id='slaVencido' class="badge badge-error"><a style="color: #FFF" href="<?php echo $this->baseUrl()?>/financeiro/movimentacoes/despesas-vencidas">ver</a></span>
						</div>
					<?php endif;?>
					<?php if( $this->vencendo > 0 ):?>
						<div class="alert alert-info">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<h4>Despesas Vencendo!</h4>
							Exite(m) <span class="badge badge-warning"><?php echo $this->vencendo?></span> Despesas vencendo hoje! <span id='slaVencido' class="badge badge-error"><a style="color: #FFF" href="<?php echo $this->baseUrl()?>/financeiro/movimentacoes/despesas-vencendo">ver</a></span>
						</div>
					<?php endif;?>
					<div>
						<ul class="nav nav-tabs">
							<li class="active"><a href="#movimentacoes" data-toggle="tab">Movimentaçoes</a></li>
							<li><a href="#graficos" data-toggle="tab">Gráficos</a></li>
						</ul>
						<div id="myTabContent" class="tab-content">
							<div class="tab-pane active in" id="movimentacoes">

								<div align="right"style="width: 250px; float: left; margin: 50px">
									<div class="dl">
										<div class="brand">
											<h2>Receitas</h2>
										</div>
										<div class="discount peter-river">
											<?php echo 'R$ '.$this->receitas?>
										</div>
										<div class="descr">
											<strong> Provisão: </strong>
											<?php
											$class = ($this->provisoesReceitas < 0) ? "btn-danger badge" : "btn-success badge";
											echo '<a class="'.$class.'">R$ '.$this->provisoesReceitas.'</a>';
											?>
										</div>
									</div>
								</div>
								<div align="right"style="width: 250px; float: left; margin: 50px">
									<div class="dl">
										<div class="brand">
											<h2>Despesas</h2>
										</div>
										<div class="discount peter-river">
											<?php echo 'R$ '.$this->despesas?>
										</div>
										<div class="descr">
											<strong> Provisão: </strong>
											<?php
											$class = ($this->provisoesDespesas < 0) ? "btn-danger badge" : "btn-success badge";
											echo '<a class="'.$class.'">R$ '.$this->provisoesDespesas.'</a>';
											?>
										</div>
									</div>
								</div>
								<div align="right"style="width: 250px; float: left; margin: 50px">
									<div class="dl">
										<div class="brand">
											<h2>Saldo</h2>
										</div>
										<div class="discount <?php echo ($this->saldo < 0) ? 'alizarin' : 'emerald'; ?>">
											<?php echo 'R$ '.$this->saldo?>
										</div>
										<div class="descr">
											<strong> Provisão: </strong>
											<?php
												$class = ($this->provisoesTotal < 0) ? "btn-danger badge" : "btn-success badge";
												echo '<a class="'.$class.'">R$ '.$this->provisoesTotal.'</a>';
											?>
										</div>
									</div>
								</div>
								<br style="clear: both;">
								<br style="clear: both;">
							</div>
							<div class="tab-pane fade" id="graficos"></div>
						</div>
					</div>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->