<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/email/index/index.js" type="text/javascript"></script>
<style>

	.mail-box {
		border-collapse: collapse;
		border-spacing: 0;
		display: table;d
		table-layout: fixed;
		width: 100%;
	}
	.mail-box aside {
		display: table-cell;
		float: none;
		height: 100%;
		padding: 0;
		vertical-align: top;
	}
	.mail-box .sm-side {
		background: none repeat scroll 0 0 #e5e8ef;
		border-radius: 4px 0 0 4px;
		width: 25%;
	}
	.mail-box .lg-side {
		background: none repeat scroll 0 0 #fff;
		border-radius: 0 4px 4px 0;
		width: 75%;
	}
	.mail-box .sm-side .user-head {
		background: none repeat scroll 0 0 #00a8b3;
		border-radius: 4px 0 0;
		color: #fff;
		min-height: 80px;
		padding: 10px;
	}
	.user-head .inbox-avatar {
		float: left;
		width: 65px;
	}

	.user-head .user-name {
		display: inline-block;
		margin: 0 0 0 10px;
	}
	.user-head .user-name h5 {
		font-size: 14px;
		font-weight: 300;
		margin-bottom: 0;
		margin-top: 15px;
	}
	.user-head .user-name h5 a {
		color: #fff;
	}
	.user-head .user-name span a {
		color: #87e2e7;
		font-size: 12px;
	}
	a.mail-dropdown {
		background: none repeat scroll 0 0 #80d3d9;
		border-radius: 2px;
		color: #01a7b3;
		font-size: 10px;
		margin-top: 20px;
		padding: 3px 5px;
	}
	.inbox-body {
		padding: 20px;
	}
	.btn-compose {
		background: none repeat scroll 0 0 #ff6c60;
		color: #fff;
		padding: 12px 0;
		text-align: center;
		width: 100%;
	}
	.btn-compose:hover {
		background: none repeat scroll 0 0 #f5675c;
		color: #fff;
	}
	ul.inbox-nav {
		display: inline-block;
		margin: 0;
		padding: 0;
		width: 100%;
	}
	.inbox-divider {
		border-bottom: 1px solid #d5d8df;
	}
	ul.inbox-nav li {
		display: inline-block;
		line-height: 45px;
		width: 100%;
	}
	ul.inbox-nav li a {
		color: #6a6a6a;
		display: inline-block;
		line-height: 45px;
		padding: 0 20px;
		width: 100%;
	}
	ul.inbox-nav li a:hover, ul.inbox-nav li.active a, ul.inbox-nav li a:focus {
		background: none repeat scroll 0 0 #d5d7de;
		color: #6a6a6a;
	}
	ul.inbox-nav li a i {
		color: #6a6a6a;
		font-size: 16px;
		padding-right: 10px;
	}
	ul.inbox-nav li a span.label {
		margin-top: 13px;
	}
	ul.labels-info li h4 {
		color: #5c5c5e;
		font-size: 13px;
		padding-left: 15px;
		padding-right: 15px;
		padding-top: 5px;
		text-transform: uppercase;
	}
	ul.labels-info li {
		margin: 0;
	}
	ul.labels-info li a {
		border-radius: 0;
		color: #6a6a6a;
	}
	ul.labels-info li a:hover, ul.labels-info li a:focus {
		background: none repeat scroll 0 0 #d5d7de;
		color: #6a6a6a;
	}
	ul.labels-info li a i {
		padding-right: 10px;
	}
	.nav.nav-pills.nav-stacked.labels-info p {
		color: #9d9f9e;
		font-size: 11px;
		margin-bottom: 0;
		padding: 0 22px;
	}
	.inbox-head {
		background: none repeat scroll 0 0 #41cac0;
		border-radius: 0 4px 0 0;
		color: #fff;
		min-height: 80px;
		padding: 20px;
	}
	.inbox-head h3 {
		display: inline-block;
		font-weight: 300;
		margin: 0;
		padding-top: 6px;
	}
	.inbox-head .sr-input {
		border: medium none;
		border-radius: 4px 0 0 4px;
		box-shadow: none;
		color: #8a8a8a;
		float: left;
		height: 40px;
		padding: 0 10px;
	}
	.inbox-head .sr-btn {
		background: none repeat scroll 0 0 #00a6b2;
		border: medium none;
		border-radius: 0 4px 4px 0;
		color: #fff;
		height: 40px;
		padding: 0 20px;
	}
	.table-inbox {
		border: 1px solid #d3d3d3;
		margin-bottom: 0;
	}
	.table-inbox tr td {
		padding: 12px !important;
	}
	.table-inbox tr td:hover {
		cursor: pointer;
	}
	.table-inbox tr td .fa-star.inbox-started, .table-inbox tr td .fa-star:hover {
		color: #f78a09;
	}
	.table-inbox tr td .fa-star {
		color: #d5d5d5;
	}
	.table-inbox tr.unread td {
		background: none repeat scroll 0 0 #f7f7f7;
		font-weight: 600;
	}
	ul.inbox-pagination {
		float: right;
	}
	ul.inbox-pagination li {
		float: left;
	}
	.mail-option {
		display: inline-block;
		margin-bottom: 10px;
		width: 100%;
	}
	.mail-option .chk-all, .mail-option .btn-group {
		margin-right: 5px;
	}
	.mail-option .chk-all, .mail-option .btn-group a.btn {
		background: none repeat scroll 0 0 #fcfcfc;
		border: 1px solid #e7e7e7;
		border-radius: 3px !important;
		color: #afafaf;
		display: inline-block;
		padding: 5px 10px;
	}
	.inbox-pagination a.np-btn {
		background: none repeat scroll 0 0 #fcfcfc;
		border: 1px solid #e7e7e7;
		border-radius: 3px !important;
		color: #afafaf;
		display: inline-block;
		padding: 5px 15px;
	}
	.mail-option .chk-all input[type="checkbox"] {
		margin-top: 0;
	}
	.mail-option .btn-group a.all {
		border: medium none;
		padding: 0;
	}
	.inbox-pagination a.np-btn {
		margin-left: 5px;
	}
	.inbox-pagination li span {
		display: inline-block;
		margin-right: 5px;
		margin-top: 7px;
	}
	.fileinput-button {
		background: none repeat scroll 0 0 #eeeeee;
		border: 1px solid #e6e6e6;
	}
	.inbox-body .modal .modal-body input, .inbox-body .modal .modal-body textarea {
		border: 1px solid #e6e6e6;
		box-shadow: none;
	}
	.btn-send, .btn-send:hover {
		background: none repeat scroll 0 0 #00a8b3;
		color: #fff;
	}
	.btn-send:hover {
		background: none repeat scroll 0 0 #009da7;
	}
	.modal-header h4.modal-title {
		font-family: "Open Sans",sans-serif;
		font-weight: 300;
	}
	.modal-body label {
		font-family: "Open Sans",sans-serif;
		font-weight: 400;
	}
	.heading-inbox h4 {
		border-bottom: 1px solid #ddd;
		color: #444;
		font-size: 18px;
		margin-top: 20px;
		padding-bottom: 10px;
	}
	.sender-info {
		margin-bottom: 20px;
	}
	.sender-info img {
		height: 30px;
		width: 30px;
	}
	.sender-dropdown {
		background: none repeat scroll 0 0 #eaeaea;
		color: #777;
		font-size: 10px;
		padding: 0 3px;
	}
	.view-mail a {
		color: #ff6c60;
	}
	.attachment-mail {
		margin-top: 30px;
	}
	.attachment-mail ul {
		display: inline-block;
		margin-bottom: 30px;
		width: 100%;
	}
	.attachment-mail ul li {
		float: left;
		margin-bottom: 10px;
		margin-right: 10px;
		width: 150px;
	}
	.attachment-mail ul li img {
		width: 100%;
	}
	.attachment-mail ul li span {
		float: right;
	}
	.attachment-mail .file-name {
		float: left;
	}
	.attachment-mail .links {
		display: inline-block;
		width: 100%;
	}

	.fileinput-button {
		float: left;
		margin-right: 4px;
		overflow: hidden;
		position: relative;
	}
	.fileinput-button input {
		cursor: pointer;
		direction: ltr;
		font-size: 23px;
		margin: 0;
		opacity: 0;
		position: absolute;
		right: 0;
		top: 0;
		transform: translate(-300px, 0px) scale(4);
	}
	.fileupload-buttonbar .btn, .fileupload-buttonbar .toggle {
		margin-bottom: 5px;
	}
	.files .progress {
		width: 200px;
	}
	.fileupload-processing .fileupload-loading {
		display: block;
	}
	* html .fileinput-button {
		line-height: 24px;
		margin: 1px -3px 0 0;
	}
	* + html .fileinput-button {
		margin: 1px 0 0;
		padding: 2px 15px;
	}
	@media (max-width: 767px) {
		.files .btn span {
			display: none;
		}
		.files .preview * {
			width: 40px;
		}
		.files .name * {
			display: inline-block;
			width: 80px;
			word-wrap: break-word;
		}
		.files .progress {
			width: 20px;
		}
		.files .delete {
			width: 60px;
		}
	}
	ul {
		list-style-type: none;
		padding: 0px;
		margin: 0px;
	}

	@media (min-width: 768px) {
		.modal-dialog {
			width: 600px;
			margin: 30px auto;
		}
		.modal-content {
			-webkit-box-shadow: 0 5px 15px rgba(0, 0, 0, .5);
			box-shadow: 0 5px 15px rgba(0, 0, 0, .5);
		}
		.modal-sm {
			width: 300px;
		}
		.modal-xy {  // custom
		width: xxxpx;
		}
	}
	@media (min-width: 992px) {
		.modal-lg {
			width: 900px;
		}
	}
</style>
<div>
	<link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
	<div class="mail-box">
		<aside class="sm-side">
			<div class="user-head">
				<div class="user-name">
					<h5><a href="#"><?php echo $this->user['user']->ds_login?></a></h5>
					<span><a href="#"><?php echo $this->user['user']->no_perfil?></a></span>
				</div>
				<a class="mail-dropdown pull-right" href="javascript:;">
					<i class="fa fa-chevron-down"></i>
				</a>
			</div>
			<div class="inbox-body">
				<a href="#modalCadastroEmail" data-toggle="modal"  title="Escrever"    class="btn btn-compose">
					ESCREVER
				</a>
				<!-- Modal -->
				<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modalCadastroEmail" class="modal fade" style="display: none;">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
								<h4 class="modal-title">ESCREVER</h4>
							</div>
							<div class="modal-body">
								<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
									<div class="form-group">
										<label class="col-lg-2 control-label">Para</label>
										<div class="col-lg-10">
											<?php echo $this->usuarios();?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-lg-2 control-label">Assunto</label>
										<div class="col-lg-10">
											<input type="text" placeholder="" id="ds_assunto" name="ds_assunto" class="form-control">
										</div>
									</div>
									<div class="form-group">
										<label class="col-lg-2 control-label">Mensagem</label>
										<div class="col-lg-10">
											<textarea rows="10" cols="30" class="form-control" id="mensagem" name="mensagem"></textarea>
										</div>
									</div>

									<div class="form-group">
										<div class="col-lg-offset-2 col-lg-10">
											<div class="col-md-12">
												<div class="row">
													<div class="control-group" id="fields">
														<div class="controls">

															<div class="entry input-group col-xs-3">
																<input class="btn btn-default" name="fields[]" type="file">
																<span class="input-group-btn">
																	<button class="btn btn-grey btn-add" type="button">
																		<span class="glyphicon glyphicon-plus"></span>
																	</button>
																</span>
															</div>

														</div>

													</div>
												</div>
											</div>
											<button class="btn btn-send" type="submit">Enviar</button>
										</div>
									</div>
								</form>
							</div>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
				<!-- Modal -->
				<div aria-hidden="true" aria-labelledby="modalCadastroEmail" role="dialog" tabindex="-1" id="modalVisualizarEmail" class="modal fade" style="display: none;">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
								<h4 class="modal-title">VISUALIAR</h4>
							</div>
							<div class="modal-body">
								<form role="form" class="form-horizontal">
									<div class="form-group">
										<label class="col-lg-2 control-label">Para</label>
										<div class="col-lg-10">
											<?php echo $this->usuarios();?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-lg-2 control-label">Assunto</label>
										<div class="col-lg-10">
											<input type="text" placeholder="" id="inputPassword1" class="form-control">
										</div>
									</div>
									<div class="form-group">
										<label class="col-lg-2 control-label">Mensagem</label>
										<div class="col-lg-10">
											<textarea rows="10" cols="30" class="form-control" id="" name=""></textarea>
										</div>
									</div>

									<div class="form-group">
										<div class="col-lg-offset-2 col-lg-10">
                                                      <span class="btn green fileinput-button">
                                                        <i class="fa fa-plus fa fa-white"></i>
                                                        <span>Anexar</span>
                                                        <input type="file" name="files[]" multiple="">
                                                      </span>
											<button class="btn btn-send" type="submit">Enviar</button>
										</div>
									</div>
								</form>
							</div>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
			</div>
			<ul class="inbox-nav inbox-divider">
				<li class="active">
					<a href="<?php echo $this->baseUrl()?>/email/index/index"><i class="fa fa-inbox"></i> Entrada <span class="label label-success pull-right"><?php echo $this->cNaoLidos?></span></a>

				</li>
				<li>
					<a href="<?php echo $this->baseUrl()?>/email/index/index/st_enviado/1"><i class="fa fa-envelope-o"></i> Enviados <span class="label label-primary pull-right"><?php echo $this->cEnviados?></span></a>
				</li>
				<li>
					<a href="<?php echo $this->baseUrl()?>/email/index/index/st_importante/1"><i class="fa fa-bookmark-o"></i> Importante <span class="label label-warning pull-right"><?php echo $this->cImportante?></span></a>
				</li>
				<li>
					<a href="<?php echo $this->baseUrl()?>/email/index/index/st_encaminhado/1"><i class=" fa fa-external-link"></i> Encaminhados <span class="label label-info pull-right"><?php echo $this->cEncaminhados?></span></a>
				</li>
				<li>
					<a href="<?php echo $this->baseUrl()?>/email/index/index/st_deletado/1"><i class=" fa fa-trash-o"></i> Deletados <span class="label label-danger pull-right"><?php echo $this->cDeletados?></span></a>
				</li>
			</ul>

		</aside>
		<aside class="lg-side">
			<div class="inbox-head">
				<h3>Caixa de Entrada</h3>
				<form action="#" class="pull-right position">
					<div class="input-append">
						<input type="text" class="sr-input" placeholder="Procurar E-Mail">
						<button class="btn sr-btn" type="button"><i class="fa fa-search"></i></button>
					</div>
				</form>
			</div>
			<div class="inbox-body">
				<div class="mail-option">
					<div class="chk-all">
						<input type="checkbox" class="mail-checkbox mail-group-checkbox" id="marcarTodos">
						<div class="btn-group">
							<a data-toggle="dropdown" href="#" class="btn mini all" aria-expanded="false">
								Todos
								<i class="fa fa-angle-down "></i>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#"> Não</a></li>
								<li><a href="#" onclick="moverLidos(1)"> Lidos</a></li>
								<li><a href="#" onclick="moverLidos(0)"> Não Lidos</a></li>
							</ul>
						</div>
					</div>

					<div class="btn-group">
						<a data-original-title="Refresh" data-placement="top" data-toggle="dropdown" href="#" class="btn mini tooltips">
							<i class=" fa fa-refresh"></i>
						</a>
					</div>
					<div class="btn-group hidden-phone">
						<a data-toggle="dropdown" href="#" class="btn mini blue" aria-expanded="false">
							Mais
							<i class="fa fa-angle-down "></i>
						</a>
						<ul class="dropdown-menu">
							<li><a href="#"><i class="fa fa-pencil"></i> Marcar como Não Lido</a></li>
							<li class="divider"></li>
							<li><a href="#"><i class="fa fa-trash-o"></i> Deletar</a></li>
						</ul>
					</div>
					<div class="btn-group">
						<a data-toggle="dropdown" href="#" class="btn mini blue">
							Mover para
							<i class="fa fa-angle-down "></i>
						</a>
						<ul class="dropdown-menu">
							<li><a href="#" onclick="moverLidos(1)"><i class="fa fa-pencil"></i> Lidos</a></li>
							<li class="divider"></li>
							<li><a href="#" onclick="moverDeletados()"><i class="fa fa-trash-o"></i> Deletados</a></li>
						</ul>
					</div>

					<ul class="unstyled inbox-pagination">
						<li><?php	echo $this->paginator;?><span><?php echo $this->cFiltro?> de <?php echo $this->cTotal?></span></li>
					</ul>
				</div>
				<table class="table table-inbox table-hover">
					<tbody>
					<?php
					if(sizeof($this->paginator)){
						foreach($this->paginator as $email){
						?>
					<tr class="<?php if(empty($email['st_lido'])):?>unread<?php endif;?>">
						<td class="inbox-small-cells">
							<input type="checkbox" class="mail-checkbox" value="<?php echo $email['co_email']?>">
						</td>
						<td class="inbox-small-cells"><i onclick="importante(<?php echo $email['co_email']?>, <?php echo empty($email['st_importante']) ? 1 : 0;?>)" class="fa fa-star<?php if(!empty($email['st_importante'])):?> inbox-started<?php endif;?>"></i></td>
						<td class="view-message <?php if(!empty($email['st_lido'])):?> dont-show<?php endif;?>"><?php echo $email['no_usuario']?></td>
						<td class="view-message "><?php echo $email['ds_assunto']?></td>
						<td class="view-message  inbox-small-cells"><?php if(!empty($email['ds_anexo'])):?><i class="fa fa-paperclip"></i><?php endif?></td>
						<td class="view-message  text-right"><?php echo retornaDmyHora($email['dt_cadastro'])?></td>
					</tr>
					<?php }} ?>
					</tbody>
				</table>
			</div>
		</aside>
	</div>
</div>
<form id="frmEdit" name="frmEdit" method="post">
	<input type="hidden" name="co_email" id="co_email" value="<?php echo $this->co_email?>">

	<input type="hidden" name="st_importante" id="st_importante" value="<?php echo $this->st_importante?>">
	<input type="hidden" name="co_importante" id="co_importante" value="<?php echo $this->importante?>">

	<input type="hidden" name="st_enviado" value="<?php echo $this->st_enviado?>">
	<input type="hidden" name="enviado" value="<?php echo $this->enviado?>">
	<input type="hidden" name="st_encaminhado" value="<?php echo $this->st_encaminhado?>">
	<input type="hidden" name="encaminhado" value="<?php echo $this->encaminhado?>">
	<input type="hidden" name="st_deletado" value="<?php echo $this->st_deletado?>">
	<input type="hidden" name="deletado" value="<?php echo $this->deletado?>">
	<input type="hidden" name="st_urgente" value="<?php echo $this->st_urgente?>">
	<input type="hidden" name="urgente" value="<?php echo $this->urgente?>">
</form>