<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/servicos/index.js" type="text/javascript"></script>

<div class="navbar">
	<div class="navbar-inner">
		<h3>Administração
		<button style="float: right" data-toggle="modal" href="#modalCadastro" class="btn btn-primary" type="button" id="novoRegistro">Novo Serviço</button> &nbsp;&nbsp;
		<button style="float: right;margin-right: 10px;" data-toggle="modal" href="#modalTipoContrato" class="btn btn-primary" type="button" id="tipoContrato">Tipo de Contrato</button></h3>
	</div>
</div>
	<div id="message_success" class="alert alert-success hide">
    <h4 class="alert-heading"><?php echo $_SESSION['message']['message']?></h4>
    </div>
    
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message']['message']; ?>
    </div>

<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Serviços</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
					<tr>
						<th>ID</th>
						<th>Serviço</th>
						<th>Sigla</th>
						<th>Tipo</th>
						<th>Data de Cadastro</th>
						<th>Opções</th>
					</tr>
					</thead>
					<tbody>
					<?php
					if( sizeof($this->arrServicos) ):
						foreach ($this->arrServicos as $servico) :
							?>
							<tr>
								<td><?php echo $servico['co_servico']?></td>
								<td><?php echo $servico['no_servico'] ?></td>
								<td><?php echo $servico['sg_servico'] ?></td>
								<td><?php echo ($servico['tp_servico'] == 'P' ) ? 'Projeto' : 'Pós-Outorga' ?></td>
								<td><?php echo retornaDmy( $servico['dt_cadastro'] ) ?></td>
								<td>
									<a href="#" title="Editar Serviço" onclick="editar('<?php echo $servico['co_servico']?>')"><i class="glyphicon glyphicon-edit"></i></a>
									<a href="#" title="Excluir Serviço" onclick="$('#co_modal').val(<?php echo $servico['co_servico']?>);$('#confirm-dialog').modal('show');"><i class="glyphicon glyphicon-trash"></i></a>
								</td>
							</tr>
						<?php endforeach;
					else :
						?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->


	</div><!-- /.col -->
</div><!-- /.row -->

<!-- Modal -->
<div class="modal" id="modalCadastro">
	<form name="frmCadServico" id="frmCadServico">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><i
						aria-hidden="true">&times;</i></button>
				<h4 class="modal-title" id="tituloModalExistente">Cadastrar Serviço</h4>
			</div>
			<div class="modal-body">
				<p>
					<div class="well bs-component">

							<div class="form-group">
								<label class="col-lg-3 control-label" for="no_servico">Nome:</label>
								<div class="col-lg-9">
									<input type="hidden" name="co_servico" id="co_servico">
									<input type="text" required class="input-xxlarge" name="no_servico" id="no_servico" value="">
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="form-group">
								<label class="col-lg-4 control-label" for="no_servico">Tipo de Serviço:</label>
								<div class="col-lg-8">
									<input type="radio" required name="tp_servico" id="tp_servico_posoutorga" value="O">Pós-Outorga
									<input type="radio" required name="tp_servico" id="tp_servico_projeto" value="P">Projeto<br>
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="form-group">
								<label class="col-lg-3 control-label" for="sg_servico">Sigla:</label>
								<div class="col-lg-9">
									<input type="text" class="input-xxlarge" name="sg_servico" id="sg_servico" value="">
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="inputNome">Modelo de Contrato:</label>
								<div class="col-lg-9">
									<textarea id="ds_modelo" required name="ds_modelo" rows="3" class="form-control"></textarea>
									<input type="hidden" name="co_modelo_contrato_servico" id="co_modelo_contrato_servico">
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="inputNome">Descrição:</label>
								<div class="col-lg-9">
									<textarea id="ds_servico" required name="ds_servico" rows="3" class="form-control"></textarea>
								</div>
							</div>

					<div class="clear">&nbsp;</div>
				</div>
				</p>
				<div class="clear">&nbsp;</div>

			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
				<button type="submit" id="btnSalvarServico" class="btn btn-primary">Salvar</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->


<!-- Modal -->
<div class="modal" id="modalTipoContrato">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
						aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="tituloModalExistente">Cadastrar Tipo de Contrato</h4>
			</div>
			<div class="modal-body">
				<p>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputNome">Descrição</label>
						<div class="col-lg-10">
							<input type="hidden" name="contrato" id="contrato">
							<input type="text" required="" name="ds_tipo_contrato" id="ds_tipo_contrato" placeholder="DESCRIÇÃO"><br>
						</div>
					</div>
				<br class="clear">
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
				<button type="submit" class="btn btn-primary">Salvar</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->




<!-- Modal -->
  <div class="modal hide" id="modalListaClausula">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalClausula').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Visualizar Cláusulas</h4>
        </div>
        <div id="modalbodyClausulas" class="modal-body">
				
		</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <div class="modal hide fade" id="confirm-dialog">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3>Confirmar</h3>
	</div>
	<div class="modal-body">Deseja deletar este registro?<input type="hidden" id="co_modal"></div>
	<div class="modal-footer">
		<a style="cursor: pointer" onclick="deletar()" class="btn btn-danger">Ok</a> 
		<a style="cursor: pointer"	class="btn btn-cancel" data-dismiss="modal">Cancelar</a>
	</div>
</div>