<?php $this->headScript()->appendFile($this->baseUrl().'/js/administracao/clientes/index.js')?>
<style>
.modal {
	width: 800px;
	left: 40%;
}
</style>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Clientes ::.
		<button style="float: right" class="btn btn-danger" type="button" id="novoRegistro">Novo Registro</button></h3>
	</div>
</div>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo 'Operação realizada com sucesso!'?></h4>
    </div>
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message'];?>
    </div>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'sucesso' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome/Razão Social</th>
			<th>CPF/CNPJ</th>
			<th>Telefone</th>
			<th>E-mail</th>
			<th>Opções&nbsp;&nbsp;&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $cliente) : 
		$tp_pessoa = empty($cliente['nu_cnpj']) ? 'pf' : 'pj';
	?>
		<tr>
			<td><?php echo $cliente['co_pessoa']?></td>
			<td><?php echo empty($cliente['no_pessoa_fisica']) ? $cliente['no_razao_social'] : $cliente['no_pessoa_fisica'];?></td>
			<td><?php echo empty($cliente['nu_cnpj']) ? formataCPF( $cliente['nu_cpf'] ) : formataCNPJ( $cliente['nu_cnpj'] );?></td>
			<td><?php echo $cliente['nu_telefone_1']?></td>
			<td><?php echo $cliente['ds_email']?></td>
				<td>
				<a onclick="$('#co_modal').val(<?php echo $cliente['co_pessoa']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-search"></i></a>
				<a onclick="editar('<?php echo $cliente['co_pessoa']?>', '<?php echo $tp_pessoa?>')" href="#"><i class="icon-edit"></i></a>
				<a onclick="$('#co_modal').val(<?php echo $cliente['co_pessoa']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>