<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/contrato/gerar.js" type="text/javascript"></script>

<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: CONTRATO <?php echo $this->arrContrato['co_contrato']?> ::.
			<button style="float: right;margin-right: 10px;" class="btn btn-primary" type="button" id="btnGravarContrato"> <i class="glyphicon glyphicon-floppy-disk"></i> <b>Gravar Contrato</b></button> &nbsp;&nbsp;
			<form id="frmGravarContrato">
				<input type="hidden" name="co_pessoa" value="<?php echo $this->dados['pessoa_juridica']['co_pessoa_juridica']?>">
				<input type="hidden" name="tp_pessoa" value="<?php echo empty( $this->dados['co_pessoa_juridica'] ) ? 'PF' : 'PJ';?>">
				<input type="hidden" name="co_servico" value="<?php echo $this->dados['co_servico']?>">
				<input type="hidden" name="co_forma_pagamento" value="<?php echo $this->dados['co_forma_pagamento']?>">
				<input type="hidden" name="ds_valor" value="<?php echo $this->dados['ds_valor']?>">
				<input type="hidden" name="ds_contrato" id="ds_contrato" value="">
			</form>
		</h3>
		<div id="message" class="alert alert-warning">
			<h4 class="alert-heading"><i class="glyphicon glyphicon-exclamation-sign"></i> Verifique o contrato e clique no botão "Gravar Contrato" para gerar as parcelas.
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><i aria-hidden="true">&times;</i></button>
			</h4>
		</div>
	</div>
	
</div>
<div id="conteudo">
	<div class="control-group">
		<div class="col-lg-12">
			<label class="col-lg-2 control-label" for="no_servico">Cliente:</label>
			<div class="col-lg-10">
				<?php echo $this->dados['pessoa_juridica']['no_razao_social']?>
			</div>
		</div>
		<div class="col-lg-12">
			<label class="col-lg-2 control-label" for="no_servico">Serviço:</label>
			<div class="col-lg-10">
				<?php echo $this->dados['modeloContrato']['no_servico']?>
			</div>
		</div>
		<div class="col-lg-12">
			<label class="col-lg-2 control-label" for="no_servico">Forma de Pagamento:</label>
			<div class="col-lg-10">
				<?php echo $this->dados['formaPagamento']['ds_forma_pagamento']?>
			</div>
		</div>
		<div class="col-lg-12">
			<label class="col-lg-2 control-label" for="no_servico">Valor Total:</label>
			<div class="col-lg-10">
				<?php echo 'R$ '.moeda( $this->dados['ds_valor'])?>
			</div>
		</div>
		<div class="col-lg-12">
			<label class="col-lg-2 control-label" for="no_servico">Modelo:</label>
			<div class="col-lg-10">
				<textarea id="ds_modelo" name="ds_modelo" rows="25">
					<?php echo $this->dados['modeloContrato']['ds_modelo']?>
				</textarea>
			</div>
	</div>
	<div class="clear">&nbsp;</div>
</div>