<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/contrato/index.js" type="text/javascript"></script>
<div class="navbar">
	<div class="navbar-inner">
		<h3>Administração
			<button style="float: right" data-toggle="modal" href="#modalCadastro" class="btn btn-primary" type="button" id="novoRegistro">Novo Contrato</button> &nbsp;&nbsp;
			<button style="float: right;margin-right: 10px;" data-toggle="modal" href="#modalFormaPagamento" class="btn btn-primary" type="button" id="novoRegistro">Formas de pagamento</button> &nbsp;&nbsp;
	</div>
</div>


<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Contratos</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
					<tr>
						<th>ID</th>
						<th>Plano</th>
						<th>Forma de Pagamento</th>
						<th>Valor</th>
						<th>Data de Cadastro</th>
						<th>Status</th>
						<th>Opções</th>
					</tr>
					</thead>
					<tbody>
					<?php
					if( sizeof($this->arrContrato) ):
						foreach ($this->arrContrato as $contrato) :
							?>
							<tr class="<?php echo retornaClassStatus( $contrato['st_status'] )?>">
								<td><?php echo $contrato['co_contrato']?></td>
								<td><?php echo $contrato['ds_plano'] ?></td>
								<td><?php echo $contrato['ds_forma_pagamento'] ?></td>
								<td><?php echo 'R$ '.formatValShow( $contrato['ds_valor'] )?></td>
								<td><?php echo retornaDmyHora( $contrato['dt_cadastro'] ) ?></td>
								<td><?php echo retornaStatus( $contrato['st_status'] )?></td>
								<td>
									<!--  <a href="#" onclick="editar('<?php echo $contrato['co_contrato']?>')"><i class="icon-edit"></i></a>-->
									<!-- <a href="#" title="Parcelas" onclick="parcelas('<?php echo $contrato['co_contrato']?>')"><img src="<?php echo $this->baseUrl()?>/images/credito.png"></a> -->
									<?php if( $contrato['st_status'] == 1 ):?>
										<a href="#" title="Gerar Contrato" onclick="gerarContrato('<?php echo $contrato['co_contrato']?>')"><img src="<?php echo $this->baseUrl()?>/images/contrato.png"></a>
										<a href="#" title="checklist" onclick="checklist('<?php echo $contrato['co_contrato']?>')"><img src="<?php echo $this->baseUrl()?>/images/checklist.png"></a>
									<?php endif;?>
									<!-- <a href="#" onclick="$('#co_modal').val(<?php echo $contrato['co_contrato']?>);$('#confirm-dialog').modal('show');"><i class="icon-trash"></i></a>-->
								</td>
							</tr>
						<?php endforeach;
					endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->


	</div><!-- /.col -->
</div><!-- /.row -->

<!-- Modal -->
<div class="modal" id="modalCadastro">
	<form name="frmCadContrato" id="frmCadContrato" method="post">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Contrato</h4>
				</div>
				<div class="modal-body">
					<p>

							<div class="control-group">
								<label class="col-lg-3 control-label" for="no_servico">Cliente:</label>
								<div class="col-lg-9">
									<?php echo $this->cliente(null, 'required="required"');?>
									<input type="hidden" id="tp_pessoa" name="tp_pessoa" value="">
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="no_servico">Serviço:</label>
								<div class="col-lg-9">
									<?php echo $this->servico(null, null, array('tp_servico'=>'P'))?>
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group plano" style="display: none">
								<label class="col-lg-3 control-label" for="no_servico">Plano:</label>
								<div class="col-lg-9">
									<?php echo $this->plano(null, null, array('multiselect'=>true))?>
								</div>
								<div class="clear">&nbsp;</div>
							</div>
							<div class="control-group servico_pos" style="display: none">
								<label class="col-lg-3 control-label" for="no_servico">Escolha os serviços:</label>
								<div class="col-lg-9">
									<?php echo $this->servicoposoutorga()?>
								</div>
								<div class="clear">&nbsp;</div>
							</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="no_servico">Forma de Pagamento:</label>
								<div class="col-lg-9">
									<?php echo $this->FormaPagamento(null, 'required="required"');?>
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="no_servico">Valor:</label>
								<div class="col-lg-9">
									<input type="text" required="required" name="ds_valor" id="ds_valor" placeholder="VALOR"><br>
								</div>
							</div>

					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnGerarContrato" class="btn btn-primary">Gerar Contrato</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->

<!-- Modal -->
<div class="modal" id="modalFormaPagamento">
	<form name="frmFormaPagamento" id="frmFormaPagamento">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Forma de Pagamento</h4>
				</div>
				<div class="modal-body">
					<p>
						<div class="control-group">
							<label class="col-lg-2 control-label" for="no_servico">Descrição:</label>
							<div class="col-lg-10">
								<input type="text" required="required" name="ds_forma_pagamento" id="ds_forma_pagamento" placeholder="DESCRIÇÃO">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-2 control-label" for="no_servico">Parcelas:</label>
							<div class="col-lg-10">
								<input type="text" maxlength="2" class="parcelas" required="required" name="nu_parcelas" id="nu_parcelas" placeholder="PARCELAS">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-2 control-label" for="no_servico">Qtd. Dias Entrada:</label>
							<div class="col-lg-10">
								<select id="nu_qtd_dias" name="nu_qtd_dias" required='required'>
									<option value="">Selecione...</option>
									<?php for( $i=1;$i<=31;$i++):?>
										<option value="<?php echo $i?>"><?php echo $i;?></option>
									<?php endfor;?>

								</select>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnSalvarFormaPagamento" class="btn btn-primary">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->