<?php $this->headScript()->appendFile($this->baseUrl().'/js/categoria/index.js')?>
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Categorias ::.</h3>
	</div>
</div>
	<?php if(isset($_SESSION['message'])):?>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo $_SESSION['message']?></h4>
    </div>
    
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message']; ?>
    </div>
    <?php endif;?>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'sucesso' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    unset($_SESSION['message']);	    
	    ?>
	</script>
<!-- Modal -->
  <div class="modal fade" id="modalCadastro">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastro').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Categorias</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmCategororia" id="frmCategororia" class="form-horizontal" action="" method="post">
					<div class="control-group">
						<label class="control-label" for="inputNome">Descrição</label>
						<div class="controls">
							<input type="text" required="" name="titulo" id="titulo" placeholder="DESCRIÇÃO DA CATEGORIA">
							<input type="hidden" name="act" id="act" value="salvar">
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal --> 
<div class="navbar">
	<div class="navbar-inner">
		<form class="navbar-form pull-left" action="" method="post">
			<div class="input-append">
				<input class="span4" name="titulo"" id="titulo" id="appendedInputButtons" type="text" re>
				<input type="hidden" name="act" id="act" value="pesq">
				<button class="btn btn-primary" id="btnPesquisar" type="submit">Pesquisar</button>
			</div>
		</form>
		<div align="right">
			<button data-toggle="modal" href="#modalCadastro" class="btn btn-danger" id="btnNovaCategoria" type="button">Nova Categoria</button>
		</div>
	</div>
</div>

<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Código</th>
			<th>Descrição</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $categorias) : 
	?>
		<tr>
			<td><?php echo $categorias['id']?></td>
			<td><?php echo utf8_decode( $categorias['titulo'] )?></td>
			<td>
				<a onclick="editar(<?php echo $categorias['id']?>)" href="#"><i class="icon-edit"></i></a>
				<a onclick="deletar(<?php echo $categorias['id']?>)" href="#"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="4"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
