<?php $this->headScript()->appendFile($this->baseUrl().'/js/administracao/servicos/index.js')?>
<style>
.control-group.error .mce-panel {
border-color: #b94a48;
-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
-moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);

}
.modal {
	width: 800px;
	left: 40%;
}
</style>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: SERVIÇOS ::.
		<button style="float: right" data-toggle="modal" href="#modalCadastro" class="btn btn-success" type="button" id="novoRegistro">Novo Registro</button> &nbsp;&nbsp;
		<button style="float: right;margin-right: 10px;" data-toggle="modal" href="#modalTipoContrato" class="btn btn-danger" type="button" id="tipoContrato">Tipo de Contrato</button></h3>
	</div>
</div>
	<?php if(isset($_SESSION['message'])):?>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo $_SESSION['message']['message']?></h4>
    </div>
    
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message']['message']; ?>
    </div>
    <?php unset($_SESSION['message']);endif;?>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'success' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>ID</th>
			<th>Serviço</th>
			<th>Sigla</th>
			<th>Data de Cadastro</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $servico) : 
	?>
		<tr>
			<td><?php echo $servico['co_servico']?></td>
			<td><?php echo $servico['no_servico'] ?></td>
			<td><?php echo $servico['sg_servico'] ?></td>
			<td><?php echo retornaDmy( $servico['dt_cadastro'] ) ?></td>
				<td>
				<a href="#" title="Editar Serviço" onclick="editar('<?php echo $servico['co_servico']?>')"><i class="icon-edit"></i></a>
				<a href="#" title="Adicionar Cláusulas" onclick="adicionarClausula('<?php echo $servico['co_servico']?>')"><i class="icon-plus"></i></a>
				<a href="#" title="Visualizar Cláusulas" onclick="listarClausulas('<?php echo $servico['co_servico']?>')"><i class="icon-list"></i></a>
				<a href="#" title="Excluir Serviço" onclick="$('#co_modal').val(<?php echo $servico['co_servico']?>);$('#confirm-dialog').modal('show');"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
<!-- Modal -->
  <div class="modal hide" id="modalCadastro">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastro').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Serviços</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmServicos" id="frmServicos" class="form-horizontal" action="" method="post">
					<div class="control-group">
						<label class="control-label" for="inputNome">Serviço</label>
						<div class="controls">
							<input type="hidden" name="co_servico" id="co_servico">
							<input type="text" required="" name="no_servico" id="no_servico" placeholder="SERVIÇO">
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Sigla</label>
						<div class="controls">
							<input type="text" required="" name="sg_servico" id="sg_servico" placeholder="SIGLA">
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Tipo de contrato: </label>
						<div class="controls">
							<?php echo $this->tipocontrato();?>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Descrição</label>
						<div class="controls">
							<textarea name="ds_servico" id="ds_servico" rows="" cols=""></textarea>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
 <!-- Modal -->
  <div class="modal fade" id="modalTipoContrato">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastro').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Tipo de Contrato</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmTipoContrato" id="frmTipoContrato" class="form-horizontal" action="" method="post">
					<div class="control-group">
						<label class="control-label" for="inputNome">Descrição</label>
						<div class="controls">
							<input type="hidden" name="contrato" id="contrato">
							<input type="text" required="" name="ds_tipo_contrato" id="ds_tipo_contrato" placeholder="DESCRIÇÃO"><br>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<!-- Modal -->
  <div class="modal hide" id="modalListaClausula">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalClausula').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Visualizar Cláusulas</h4>
        </div>
        <div id="modalbodyClausulas" class="modal-body">
				
		</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <div class="modal hide fade" id="confirm-dialog">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3>Confirmar</h3>
	</div>
	<div class="modal-body">Deseja deletar este registro?<input type="hidden" id="co_modal"></div>
	<div class="modal-footer">
		<a style="cursor: pointer" onclick="deletar()" class="btn btn-danger">Ok</a> 
		<a style="cursor: pointer"	class="btn btn-cancel" data-dismiss="modal">Cancelar</a>
	</div>
</div>