<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/posoutorga/sici/index.js" type="text/javascript"></script>
<style>
	button{
		margin-right:10px;
	}
</style>
<div id="message_success" class="alert alert-success hide">
	<h4 class="alert-heading"></h4>
</div>

<div id="message_error" class="alert alert-error hide">
	<h4 class="alert-heading">Erro!</h4>
</div>
<div class="navbar">
	<div class="navbar-inner">
		<h3>Pós-Outorga<button style="float: right" class="btn btn-primary" type="button" id="brnGerarArquivoTopo">Gerar Arquivo</button></h3>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Sici - Gerar Arquivo</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<div class="well bs-component">
					<form name="frmGerarArquivo" id="frmGerarArquivo">
						<div class="control-group">
							<label class="col-lg-2 control-label" for="ds_plano">Cliente: </label>
							<div class="col-lg-10">
								<?php echo $this->arrPessoa['no_razao_social']?>
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-2 control-label" for="ds_plano">Mês: <span style="color:red">*</span></label>
							<div class="col-lg-10">
								<input type="text" readonly class="input-xxlarge" name="nu_mes" id="nu_mes" value="<?php echo date('m')?>">
							</div>
							<label class="col-lg-2 control-label" for="ds_plano">Ano: <span style="color:red">*</span></label>
							<div class="col-lg-10">
								<input type="text" readonly class="input-xxlarge" name="nu_ano" id="nu_ano" value="<?php echo date('Y')?>">
							</div>
						</div>
						<div class="control-group">
							<label class="col-lg-2 control-label" for="ds_plano">Fistel: <span style="color:red">*</span></label>
							<div class="col-lg-10">
								<input type="text" required="required" class="input-xxlarge" name="co_fistel" id="co_fistel">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>ITEM4 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="item4[a]" placeholder="Item a">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>ITEM5 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="item5[a]" placeholder="Item a">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>ITEM9 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano">F:</label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="item9[f][a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="item9[f][b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="item9[f][c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="item9[f][d]" placeholder="Item d">
									<input type="text" class="input-xxlarge moeda" name="item9[f][e]" placeholder="Item e">
								</div>
							</div>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano">J:</label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="item9[j][a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="item9[j][b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="item9[j][c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="item9[j][d]" placeholder="Item d">
									<input type="text" class="input-xxlarge moeda" name="item9[j][e]" placeholder="Item e">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>ITEM10 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano">F:</label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="item10[f][a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="item10[f][b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="item10[f][c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="item10[f][d]" placeholder="Item d">
								</div>
							</div>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano">J:</label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="item10[j][a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="item10[j][b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="item10[j][c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="item10[j][d]" placeholder="Item d">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IPL3 <button onclick="vincularMunicipios('ipl3')" style="float: right" class="btn btn-primary" type="button" id="munIpl3" data-toggle="modal" href="#modalCadastroServico">+ Municípios</button></legend>
							<div id="ipl3"></div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>QAIPL4SM <button onclick="vincularMunicipios('qaipl4sm')" style="float: right" class="btn btn-primary" type="button" id="munQaipl4sm" data-toggle="modal" href="#modalCadastroServico">+ Municípios</button></legend>
							<div id="qaipl4sm"></div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IPL6IM </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="ipl6im[valor]" placeholder="cod valor">
									<input type="text" class="input-xxlarge moeda" name="ipl6im[codmunicipio]" placeholder="cod municipio">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IAU1 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="ipl6im[valor]" placeholder="cod valor">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IPL1 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="ipl1[a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="ipl1[b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="ipl1[c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="ipl1[d]" placeholder="Item d">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IPL2 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="ipl2[a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="ipl2[b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="ipl2[c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="ipl2[d]" placeholder="Item d">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IEM1 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="iem1[a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="iem1[b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="iem1[c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="iem1[h]" placeholder="Item h">
									<input type="text" class="input-xxlarge moeda" name="iem1[f]" placeholder="Item f">
									<input type="text" class="input-xxlarge moeda" name="iem1[i]" placeholder="Item i">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IEM2 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="iem2[a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="iem2[b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="iem2[c]" placeholder="Item c">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IEM3 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="iem3[a]" placeholder="Item a">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IEM6 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="iem6[a]" placeholder="Item a">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IEM7 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="iem7[a]" placeholder="Item a">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<fieldset>
							<legend>IEM8 </legend>
							<div class="control-group">
								<label class="col-lg-2 control-label" for="ds_plano"></label>
								<div class="col-lg-10">
									<input type="text" class="input-xxlarge moeda" name="iem8[a]" placeholder="Item a">
									<input type="text" class="input-xxlarge moeda" name="iem8[b]" placeholder="Item b">
									<input type="text" class="input-xxlarge moeda" name="iem8[c]" placeholder="Item c">
									<input type="text" class="input-xxlarge moeda" name="iem8[d]" placeholder="Item d">
									<input type="text" class="input-xxlarge moeda" name="iem8[e]" placeholder="Item e">
								</div>
							</div>
						</fieldset>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<button style="float: right" class="btn btn-primary" type="submit" id="btnGerarArquivo">Gerar Arquivo</button>
						</div>
						<div class="clear">&nbsp;</div>
					</form>
				</div>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->

<!-- Modal -->
<div class="modal" id="modalMunicipios">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
						aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Vincular Município</h4>
			</div>
			<div class="modal-body">
				<table id="cidades" class="table table-bordered table-striped">
					<thead>
					<tr>
						<th>Código IBGE</th>
						<th>Município</th>
					</tr>
					</thead>
					<tbody>
					<?php
					if( sizeof($this->arrCidades) ):
						foreach ($this->arrCidades as $cidade) :
							?>
							<tr>
								<td style="width:10%"><input type="checkbox" name="co_cidade[]" value="<?php echo $cidade['co_cidade']?>"></td>
								<td>
									<?php echo $cidade['no_cidade']?>
								</td>
							</tr>
						<?php endforeach;
					else :
						?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="2"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
				<div class="clear">&nbsp;</div>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
				<button type="button" id="btnVincular" class="btn btn-primary">Vincular</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->