<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/posoutorga/sici/index.js" type="text/javascript"></script>
<style>
	button{
		margin-right:10px;
	}
</style>
<div id="message_success" class="alert alert-success hide">
	<h4 class="alert-heading"></h4>
</div>

<div id="message_error" class="alert alert-error hide">
	<h4 class="alert-heading">Erro!</h4>
</div>
<div class="navbar">
	<div class="navbar-inner">
		<h3>Pós-Outorga
			<button onclick="limpar()" style="float: right" class="btn btn-primary" type="button" id="novoServiço" data-toggle="modal" href="#modalCadastroServico">Novo Serviço</button></h3>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Sici</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="clientes" class="table table-bordered table-striped">
					<thead>
					<tr>
						<th>Nome/Razão Social</th>
						<th>CPF/CNPJ</th>
						<th>Telefone</th>
						<th>Whatsapp</th>
						<th>E-mail</th>
						<th>Opções</th>
					</tr>
					</thead>
					<tbody>
					<?php
					if( sizeof($this->arrClientes) ):
						foreach ($this->arrClientes as $cliente) :
							$tp_pessoa = empty($cliente['nu_cnpj']) ? 'pf' : 'pj';
							?>
							<tr>
								<td><?php echo empty($cliente['no_razao_social'] == 1) ? $cliente['no_pessoal'] : ($cliente['no_razao_social'] == $cliente['no_fantasia']) ? $cliente['no_raao_social'] : $cliente['no_pessoa'];?></td>
								<td><?php echo empty($cliente['nu_cnpj']) ? formataCPF( $cliente['nu_cpf'] ) : formataCNPJ( $cliente['nu_cnpj'] );?></td>
								<td><?php echo $cliente['nu_telefone_1']?></td>
								<td><?php echo $cliente['nu_whatsapp']?></td>
								<td><?php echo $cliente['ds_email']?></td>
								<td>
									<a title="Gerar Arquivo" onclick="gerarArquivo('<?php echo $cliente['co_pessoa']?>', '<?php echo $tp_pessoa?>')" href="#"><i class="glyphicon glyphicon-file"></i></a>
								</td>
							</tr>
						<?php endforeach;
					else :
						?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="8"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->


	</div><!-- /.col -->
</div><!-- /.row -->
<script>
	$('#clientes').dataTable( {
		"bSort": false,
		"oLanguage": {
			"oPaginate": {
				"sLast": "Ultima",
				"sNext": "Próxima",
				"sPrevious": "Anterior",
				"sEmptyTable": "Nenhum registro encontrado!",
				"sInfo": "Got a total of _TOTAL_ entries to show (_START_ to _END_)"
			}
		}
	} );
</script>