<?php $this->headScript()->appendFile($this->baseUrl().'/js/chamados/abrir.js')?>	
<style>
.modal {
  left:35%;
  width:900px;
  margin-left:-222px;
}
</style>
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Chamados ::.</h3>
	</div>
</div>
<div class="well bs-component">
	<form name="frmAbrirChamado" id="frmAbrirChamado" class="form-horizontal" method="post"  action="">
		<fieldset>
			<legend>Abrir Chamado</legend>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputEmail">Provedor: <span style="color:red">*&nbsp;</span> </label>
				<div class="col-lg-10">
					<?php echo $this->provedor($this->provedor, 'required=""');?>
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<?php if( $this->provedor ) :?>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputPassword">Cliente: <span style="color:red">*&nbsp;</span></label>
				<div class="col-lg-10">
					<?php echo $this->cliente($this->cliente,$this->provedor, 'required=""');?>
					<button id="btnRecentes" class="btn hide btn-primary" type="button">Chamados recentes</button>
				</div>
			</div>
			<div id="conteudoChamado" style="display: none;">
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="protocolo">Protocolo: </label>
				<div class="col-lg-10">
					<input type="text" name="protocolo" id="protocolo" readonly="readonly" value="<?php echo $this->protocolo?>">
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="proprietario">Proprietário: </label>
				<div class="col-lg-10">
					<input name="proprietario" id="proprietario" type="checkbox" value="1">
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="data">Data/hora: </label>
				<div class="col-lg-10">
					<input type="text" name="data" id="data" readonly="readonly" value="<?php echo Zend_Date::now()->get('dd/MM/YYYY');?>">
					<input type="text" name="hora" id="hora" readonly="readonly" value="<?php echo Zend_Date::now()->get('HH:mm:ss');?>">
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="categoria">Categoria: <span style="color:red">*&nbsp;</span> </label>
				<div class="col-lg-10">
					<?php echo $this->categoria(null, 'required=""')?>
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="status">Status: </label>
				<div class="col-lg-10">
					<?php echo $this->status(1, 'disabled="disabled"')?>
					<input type="hidden" name="id_status" id="id_status" value="1">
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="status">Problema Informado: </label>
				<div class="col-lg-10">
					<?php echo $this->problema(null, 'required=""')?>
					<input type="hidden" name="id_status" id="id_status" value="1">
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<span>Problema Constatado:</span>
			</div>
			<div class="form-group">
				<div class="col-lg-10">
					<textarea id="prob_const" name="prob_const"  rows="3" class="form-control"></textarea>
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<span>Agendamento:</span>
			</div>
			<div class="form-group">
				<div class="col-lg-10">
					<textarea id="agendamento" name="agendamento" rows="3" class="form-control"></textarea>
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<span>Observações:</span>
			</div>
			<div class="form-group">
				<div class="col-lg-10">
					<textarea id="observacoes" name="observacoes" rows="3" class="form-control"></textarea>
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputPassword">Enviar para E-mails : </label>
				<div class="col-lg-10">
					<input type="text" name="emails" id="emails" value="">
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<div class="col-lg-10 col-lg-offset-2">
					<button class="btn btn-default">Cancelar</button>
					<button id="btnSalvar" class="btn btn-primary" type="button">Salvar</button>
				</div>
			</div>
			</div>
			<?php endif;?>
		</fieldset>
	</form>
	<div class="modal hide fade modal-lg" id="modal_recentes" >
		<div class="modal-header">
			<a class="close" data-dismiss="modal">×</a>
			<h3>Chamados Recentes</h3>
		</div>
		<div id="recentes_conteudo" class="modal-body"></div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Fechar</a>
		</div>
	</div>
	
<div id="modal_excluir" class="modal hide fade" id="confirm-dialog">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3>Confirmar</h3>
	</div>
	<div class="modal-body">Deseja deletar este registro?<input type="hidden" id="co_modal"></div>
	<div class="modal-footer">
		<a style="cursor: pointer" onclick="deletar()" class="btn btn-danger">Ok</a> 
		<a style="cursor: pointer"	class="btn btn-cancel" data-dismiss="modal">Cancelar</a>
	</div>
</div>
<?php 
if( $this->cliente ):
?>
<script type="text/javascript">
	$( '#btnRecentes' ).show();
	$( '#conteudoChamado' ).show();
</script>
<?php 
endif;

?>