<?php $this->headScript()->appendFile($this->baseUrl().'/js/financeiro/contrato/dados-contrato.js')?>
<?php $this->headScript()->appendFile($this->baseUrl().'/scripts/jquery.printElement.js')?>
<?php $this->headScript()->appendFile($this->baseUrl().'/bootstrap/js/jquery.browser.js')?>

<style>
.modal {
	width: 800px;
	left: 40%;
}
.dropdown-menu{
	float: none;l
}
</style>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: CONTRATO <?php echo $this->arrContrato['co_contrato']?> ::.
			<button style="float: right;margin-right: 10px;" class="btn btn-success" type="button" id="btnImprimir"><img src="<?=Zend_Registry::get('config')->caminho->componente.'images/print.png'?>"> <b>Imprimir</b></button> &nbsp;&nbsp;
		</h3>
	</div>
	
</div>
<div id="conteudo">
<ul id="myTab" class="nav nav-tabs">
   <li class="active">
      <a href="#dados" data-toggle="tab">
         Dados do Contrato
      </a>
   </li>
   <li>
   		<a href="#parcelas" data-toggle="tab">Parcelas</a>
   </li>
</ul>
<div id="myTabContent" class="tab-content">
   <div class="tab-pane fade in active" id="dados">
      <p>
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td><b>Data de contrato:</b></td>
                        <td><?php echo $this->dados['dt_contrato']?></td>
                      </tr>
                      <tr>
                        <td><b>Serviço:</b></td>
                        <td><?php echo $this->dados['ds_servico']?></td>
                      </tr>
                      <tr>
                        <td><b>Empresa:</b></td>
                        <td>
                        <?php 
                        	echo $this->dados['no_pessoa'].'<br>';
                        	echo $this->dados['nu_documento'].'<br>';
                        	echo $this->dados['ds_endereco'].'<br>';
                        	echo $this->dados['nu_cep'].'<br>';
                        	echo formataTEL( $this->dados['nu_telefone'] ).'<br>';
                        ?>
                        </td>
                      </tr>
                      <tr>
                        <td><b>Valor:</b></td>
                        <td><?php echo 'R$ '.$this->dados['valor_contrato'].' ( '.$this->dados['valor_contrato_extenso'].' )'?></td>
                      </tr>
                      <tr>
                        <td><b>Forma de Pagamento:</b></td>
                        <td><?php echo $this->dados['ds_forma_pagamento']?></td>
                      </tr>
                    </tbody>
                  </table>
      
      </p>
   </div>
   <div class="tab-pane fade" id="parcelas">
      <p>
      	<table id="table" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th></th>
					<th>Valor</th>
					<th>Valor por extenso</th>
					<th>Data de Vencimento</th>
					<th>Status</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
			<?php 
				$i = 1;
				foreach ($this->dados['parcelas'] as $parcelas ) : 
			?>
				<tr>
					<td><?php echo $i?></td>
					<td><?php echo 'R$ '.$parcelas['valor_parcela'] ?></td>
					<td><?php echo $parcelas['valor_parcela_extenso'] ?></td>
					<td><?php echo $parcelas['data_por_extenso']?></td>
					<td class="<?php echo retornaClassStatus($parcelas['st_status'])?>"><?php echo retornaStatus($parcelas['st_status'])?></td>
					<td>
						<a title="Gerar Boleto" href="#" onclick="gerarBoleto('<?php echo $parcelas['co_contrato_parcela']?>')"><i class="icon-barcode"></i></a>
						<!-- <a href="#" title="Parcelas" onclick="parcelas('<?php echo $parcelas['co_contrato_parcela']?>')"><img src="<?php echo $this->baseUrl()?>/images/credito.png"></a> -->
						<?php if( $parcelas['st_status'] == CO_STATUS_ABERTO ):?>
							<a title="Confirmar Pagamento" href="#" onclick="confimarPagamento('<?php echo $parcelas['co_contrato_parcela']?>')"><i class="icon-check"></i></a>
						<?php endif;?>
						<!-- <a href="#" onclick="$('#co_modal').val(<?php echo $parcelas['co_contrato_parcela']?>);$('#confirm-dialog').modal('show');"><i class="icon-trash"></i></a>-->
					</td>
				</tr>
			<?php $i++;endforeach;?>
			</tbody>
		</table>
      </p>
   </div>
   <div class="tab-pane fade" id="ios2">
      <p>jMeter is an Open Source testing software. It is 100% pure 
      Java application for load and performance testing.</p>
   </div>
</div>
</div>