<?php $this->headScript()->appendFile($this->baseUrl().'/js/chamados/index.js')?>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Gravações ::.</h3>
	</div>
</div>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Provedor</th>
			<th>Duração</th>
			<th>Disposição</th>
			<th>Arquivo</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $chamado) : 
	?>
		<tr>
			<td><?php echo $chamado['clid']?></td>
			<td><?php echo $chamado['duration']?></td>
			<td><?php echo utf8_decode( $chamado['disposition'] )?></td>
			<td><?php echo utf8_decode( $chamado['userfield'] )?></td>
			<td>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
