<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/clientes/cadastro.js" type="text/javascript"></script>
<div id="message_success" class="alert alert-success hide">
	<h4 class="alert-heading"></h4>
</div>

<div id="message_error" class="alert alert-error hide">
	<h4 class="alert-heading">Erro!</h4>
</div>
<div class="well bs-component">
	<fieldset>
		<legend><h3>.:: Cadastro de Clientes ::.</h3></legend>
		<form name="frmCadCliente" id="frmCadCliente" class="form-horizontal" action="" method="post">
			<div class="form-group pj">
				<label class="col-lg-2 control-label" for="inputNome">CNPJ: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input required="required" type="text" style="width: 250px" data-inputmask='"mask": "99.999.999/9999-99"' data-mask name="data[pj][nu_cnpj]" id="nu_cnpj" value="<?php echo $this->arrPessoa['nu_cnpj']?>">
				</div>
			</div>
			<div class="clear pj">&nbsp;</div>
			<div class="form-group pf">
				<label class="col-lg-2 control-label" for="inputNome">Nome: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input name="data[pf][co_pessoa_fisica]" id="co_pessoa_fisica" type="hidden" value="<?php echo $this->arrPessoa['co_pessoa_fisica']?>" />
					<input name="data[pf][no_pessoa_fisica]" required="required" class="input-xxlarge" id="no_pessoa_fisica" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['no_pessoa_fisica']?>" />
				</div>
			</div>
			<div class="clear pj">&nbsp;</div>
			<div class="form-group pj">
				<label class="col-lg-2 control-label" for="inputNome">Razão Social: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input name="data[pj][no_razao_social]" required="required" class="input-xxlarge" id="no_razao_social" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['no_razao_social']?>" />
					<input name="data[pj][co_pessoa_juridica]" id="co_pessoa_juridica" type="hidden" value="<?php echo $this->arrPessoa['co_pessoa_juridica']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Tipo de Pessoa: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input type="radio" checked="checked" class="input" name="data[tp_pessoa]" id="tp_pessoa_pj" value="pj" style="vertical-align: middle;" /> Jurídica
					<input type="radio" class="input" id="tp_pessoa_pf" name="data[tp_pessoa]" value="pf" style="vertical-align: middle;" /> Física &nbsp;&nbsp;
				</div>
			</div>
			<div class="clear pf">&nbsp;</div>
			<div class="form-group pf">
				<label class="col-lg-2 control-label" for="inputNome">Estado Civil:</label>
				<div class="col-lg-10">
					<select name="data[pf][ds_estado_civil]" id="estado_civil">
					<option>Selecione...</option>
					<option value="Casado">Casado(a)</option>
					<option value="Solteiro">Solteiro(a)</option>
					</select>
				</div>
			</div>
			<div class="clear pf">&nbsp;</div>
			<div class="form-group pf">
				<label class="col-lg-2 control-label" for="inputNome">Nacionalidade:</label>
				<div class="col-lg-10">
					<input name="data[pf][ds_nacionalidade]" class="input-xxlarge" id="ds_nacionalidade" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['ds_nacionalidade']?>" />
				</div>
			</div>
			<div class="clear pj">&nbsp;</div>
			<div class="form-group pj">
				<label class="col-lg-2 control-label" for="inputNome">Nome Fantasia: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input name="data[pj][no_fantasia]" required="required" class="input-xxlarge" id="no_fantasia" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['no_fantasia']?>" />
				</div>
			</div>
			<div class="clear pj">&nbsp;</div>
			<div class="form-group pj">
				<label class="col-lg-2 control-label" for="inputNome">CNAE: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<div id="atividade_primaria">
						<?php if(sizeof($this->arrCnaePrimario)){?>
							<fieldset><legend>Atividade Primária</legend>
								<?php foreach($this->arrCnaePrimario as $cnae){?>
								<input type="hidden" name="data[pj][nu_cnae_primario][]" value="<?php echo $cnae['cod_cnae']?>">
									<?php echo $cnae['cod_cnae'].' - '.$cnae['ds_cnae']?>
								<?php }?>
							</fieldset>
							<div class="clear pj">&nbsp;</div>
						<?php }?>
					</div>
					<div id="atividade_secundaria">
						<?php if(sizeof($this->arrCnaeSecundario)){?>
							<fieldset><legend>Atividade Secundária</legend>
								<?php foreach($this->arrCnaeSecundario as $cnae){?>
									<input type="hidden" name="data[pj][nu_cnae_secundario][]" value="<?php echo $cnae['cod_cnae']?>">
									<?php echo $cnae['cod_cnae'].' - '.$cnae['ds_cnae']?>
									<br>
								<?php }?>
							</fieldset>
							<div class="clear pj">&nbsp;</div>
						<?php }?>
					</div>
				</div>
				<div class="clear pj">&nbsp;</div>
			</div>
			<div class="clear pf">&nbsp;</div>
			<div class="form-group pf">
				<label class="col-lg-2 control-label" for="inputNome">CPF: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input name="data[pf][nu_cpf]" required="required" class="input-medium cpf" id="nu_cpf" type="text" size="30" maxlength="15" value="<?php echo $this->arrPessoa['nu_cpf']?>" data-inputmask='"mask": "999.999.999-99"' data-mask />
				</div>
			</div>
			<div class="clear pj">&nbsp;</div>
			<div class="form-group pj">
				<label class="col-lg-2 control-label" for="inputNome">IE: </label>
				<div class="col-lg-10">
					<input name="data[pj][nu_ie]" class="input-medium" onkeyup="somente_numero(this);" id="nu_ie" type="text" size="30" maxlength="15" value="<?php echo $this->arrPessoa['nu_ie']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">CEP:</label>
				<div class="col-lg-10">
					<input class="input-medium cep" name="data[nu_cep]" data-inputmask='"mask": "99.999-999"' data-mask id="nu_cep" type="text" size="30" maxlength="15" value="<?php echo $this->arrPessoa['nu_cep']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Endereço:</label>
				<div class="col-lg-10">
					<input name="data[ds_endereco]" class="input-xxlarge" id="ds_endereco" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['ds_endereco']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Bairro:</label>
				<div class="col-lg-10">
					<input name="data[no_bairro]" class="input-xxlarge" id="no_bairro" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['no_bairro']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Estado: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<?php echo $this->estados($this->arrPessoa['sg_uf'], 'required="required"', array('cadastro' => true));?>
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Cidade: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					<input class="input-xlarge" name="data[no_cidade]" required="required" id="no_cidade" type="text" size="50" maxlength="100" value="<?php echo $this->arrPessoa['no_cidade']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Complemento:</label>
				<div class="col-lg-10">
					<input name="data[ds_complemento]" class="input-xlarge" id="ds_complemento" type="text" size="20" maxlength="100" value="<?php echo $this->arrPessoa['ds_complemento']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Nro:</label>
				<div class="col-lg-10">
					<input name="data[nu_endereco]" class="input-medium" id="nu_endereco" type="text" size="20" maxlength="100" value="<?php echo $this->arrPessoa['nu_endereco']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome"></label>
				<div class="col-lg-10">
					<div>O endereço de correspondência é o mesmo?</div>
					<input type="radio" name="endCorresp" id="chkEnderecoCorrespondenciaS" value="S"> Sim
					<input type="radio" name="endCorresp" id="chkEnderecoCorrespondenciaN" value="N"> Não
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group ds_endereco_correspondecia" style="display: none">
				<label class="col-lg-2 control-label" for="inputNome">Endereço de correspondência</label>
				<div class="col-lg-10">
					<input name="data[ds_endereco_correspondecia]" size="80" class="input-medium" id="ds_endereco_correspondecia" type="text" size="20" maxlength="100" value="<?php echo $this->arrPessoa['ds_endereco_correspondecia']?>" />
				</div>
			</div>
			<div class="form-group pj">
				<label class="col-lg-2 control-label" for="inputNome">Responsável: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					 <input class="input-medium" required="required" type="text" name="data[no_responsavel]" id="no_responsavel" size="80" value="<?php echo $this->arrPessoa['no_responsavel']?>" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Telefone 1: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					 <input class="input-medium" required="required" type="text" name="data[nu_telefone_1]" id="nu_telefone_1" size="80" value="<?php echo $this->arrPessoa['nu_telefone_1']?>" />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">Telefone 2:</label>
				<div class="col-lg-10">
					 <input class="input-medium" type="text" name="data[nu_telefone_2]" id="nu_telefone_2" size="80" value="<?php echo $this->arrPessoa['nu_telefone_2']?>" data-inputmask='"mask": "(99)9999-9999"' data-mask />
				</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<label class="col-lg-2 control-label" for="inputNome">E-mail: <span style="color:red">*</span></label>
				<div class="col-lg-10">
					 <input class="input-xxlarge" required="required" name="data[ds_email]" id="ds_email" type="text" size="80" value="<?php echo $this->arrPessoa['ds_email']?>" />
			</div>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="form-group">
				<div align="right" class="controls">
					<button type="submit" class="btn btn-primary btn-large" id="btnSalvar">Salvar</button>
				</div>
			</div>
		</form>
	</fieldset>
</div>
<br style="clear:both;">

<!-- Modal -->
<div class="modal" id="modalCadastro">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="tituloModalExistente">Cadastro de Sócios</h4>
			</div>
			<div class="modal-body">
				<p>
					<div class="form-group">
						<label class="control-label" for="inputNome">Nome: <span style="color:red">*</span></label>
						<div class="controls">
							<input name="data[pj][no_socio]" class="input-xlarge" id="no_socio" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="form-group">
						<label class="control-label" for="inputNome">Profissão: <span style="color:red">*</span></label>
						<div class="controls">
							<input name="data[pj][ds_profissao_socio]" class="input-xlarge" id="ds_profissao_socio" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="form-group">
						<label class="control-label" for="inputNome">Cargo: <span style="color:red">*</span></label>
						<div class="controls">
							<input name="data[pj][ds_cargo_socio]" class="input-xlarge" id="ds_cargo_socio" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="form-group">
						<label class="control-label" for="inputNome">Telefone: <span style="color:red">*</span></label>
						<div class="controls">
							<input name="data[pj][nu_telefone_socio]" class="input-medium ddd_telefone" id="nu_telefone_socio" type="text" size="50" value="" data-inputmask='"mask": "(99)99999-9999"' data-mask />
						</div>
					</div>
					<div class="form-group">
						<label class="control-label" for="inputNome">Whatsapp: <span style="color:red">*</span></label>
						<div class="controls">
							<input name="data[pj][nu_whatsapp_socio]" class="input-xlarge" id="nu_whatsapp_socio" type="text" size="50" value="" data-inputmask='"mask": "(99)99999-9999"' data-mask />
						</div>
					</div>
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
				<button type="button" id="btnSalvarSocio" class="btn btn-primary">
					Adicionar
				</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal -->
<div class="modal" id="modalCadastroResponsavelTecnico">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="tituloModalExistente">Responsável Técnico</h4>
			</div>
			<div class="modal-body">
				<p id="conteudoModalExistente">
				<div class="form-group">
					<?php
					foreach ($this->arrResponsavelTecnico as $responsavel_tecnico) :
						?>
						<div>
							<input crea="<?php echo $responsavel_tecnico['nu_registro_crea']; ?>"
								   noresponsaveltecnico="<?php echo $responsavel_tecnico['no_responsavel_tecnico'] ?>"
								   type="radio" name="co_responsavel_tecnico" id=""
								   value="<?php echo $responsavel_tecnico['co_responsavel_tecnico'] ?>">
							<?php echo $responsavel_tecnico['no_responsavel_tecnico'] ?> -
							<?php echo $responsavel_tecnico['ds_area_tecnica'] ?>
						</div>
					<?php endforeach; ?>
				</div>
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
				<button type="button" id="btnAdicionarResponsavelTecnico" class="btn btn-primary">
					Adicionar
				</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->