<?php $this->headScript()->appendFile($this->baseUrl().'/js/financeiro/banco/index.js')?>
<style>
.modal {
	width: 800px;
	left: 40%;
}
</style>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: BANCO ::.
		<button style="float: right" data-toggle="modal" href="#modalCadastro" class="btn btn-danger" type="button" id="novoRegistro">Novo Registro</button></h3>
	</div>
</div>
	<?php if(isset($_SESSION['message'])):?>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo $_SESSION['message']['message']?></h4>
    </div>
    
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message']['message']; ?>
    </div>
    <?php unset($_SESSION['message']);endif;?>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'success' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Código</th>
			<th>Descrição</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $banco) : 
	?>
		<tr>
			<td><?php echo $banco['co_banco']?></td>
			<td><?php echo $banco['ds_banco'] ?></td>
				<td>
				<a href="#" onclick="editar('<?php echo $banco['co_banco']?>')"><i class="icon-edit"></i></a>
				<a href="#" onclick="$('#co_modal').val(<?php echo $banco['co_banco']?>);$('#confirm-dialog').modal('show');"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
<!-- Modal -->
  <div class="modal fade" id="modalCadastro">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastro').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de BANCO</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmCadastro" id="frmCadastro" class="form-horizontal" action="" method="post">
					<div class="control-group">
						<label class="control-label" for="inputNome">Descricao</label>
						<div class="controls">
							<input type="hidden" name="co_banco" id="co_banco">
							<input type="text" required="" name="ds_banco" id="ds_banco" placeholder="DESCRIÇÃO">
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Saldo Inicial</label>
						<div class="controls">
							<input type="text" required="" name="ds_saldo" id="ds_saldo" onchange="$(this).priceFormat();">
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Limite</label>
						<div class="controls">
							<input type="text" required="" name="ds_limite" id="ds_limite">
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <div class="modal hide fade" id="confirm-dialog">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3>Confirmar</h3>
	</div>
	<div class="modal-body">Deseja deletar este registro?<input type="hidden" id="co_modal"></div>
	<div class="modal-footer">
		<a style="cursor: pointer" onclick="deletar()" class="btn btn-danger">Ok</a> 
		<a style="cursor: pointer"	class="btn btn-cancel" data-dismiss="modal">Cancelar</a>
	</div>
</div>