<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/crea/dados.js" type="text/javascript"></script>
<div id="message_success" class="alert alert-success hide">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading"></h4>
</div>
<div id="message_error" class="alert alert-error hide">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading">Erro!</h4>
</div>

<div class="navbar">
	<div class="navbar-inner">
		<h3>Administração
	</div>
</div>

<div id="conteudo">
<?php if( $this->vencidas > 0 ):?>
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Despesas Vencidas!</h4>
    Exite(m) <span class="badge badge-warning"><?php echo $this->vencidas?></span> Despesas vencidas! <span id='slaVencido' class="badge badge-error"><a style="color: #FFF" href="<?php echo $this->baseUrl()?>/financeiro/movimentacoes/despesas-vencidas">ver</a></span>
</div>
<?php endif;?>
<?php if( $this->vencendo > 0 ):?>
<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Despesas Vencendo!</h4>
    Exite(m) <span class="badge badge-warning"><?php echo $this->vencendo?></span> Despesas vencendo hoje! <span id='slaVencido' class="badge badge-error"><a style="color: #FFF" href="<?php echo $this->baseUrl()?>/financeiro/movimentacoes/despesas-vencendo">ver</a></span>
</div>
<?php endif;?>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">.:: CREA - Responsável Técnico ::.</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#dados" data-toggle="tab">Dados</a></li>
					<li><a href="#visto" data-toggle="tab">Estados com visto</a></li>
					<li><a href="#anuidade" data-toggle="tab">Anuidade</a></li>
					<li><a href="#empresa" data-toggle="tab">Empresas</a></li>
				</ul>
				<div id="myTabContent" class="tab-content">
					<input type="hidden" id="co_contrato" name="co_contrato" value="<?php echo $this->co_contrato ?>">
					<div class="tab-pane active in" id="dados">
						<div class="row">
							<div class="modal-header">
							<table class="table table-striped" style="width: 700px;">
								<thead>
								<tr>
									<th>Nome</th>
									<th>Telefone</th>
									<th>Whatsapp</th>
									<th>E-mail</th>
									<th>CREA</th>
									<th>Tipo</th>
								</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->objResponsavel->no_responsavel_tecnico ?></td>
										<td><?php echo formataTEL($this->objResponsavel->nu_telefone) ?></td>
										<td><?php echo $this->objResponsavel->ds_skypemsn ?></td>
										<td><?php echo $this->objResponsavel->ds_email ?></td>
										<td><?php echo $this->objResponsavel->nu_registro_crea ?></td>
										<td><?php echo $this->objResponsavel->tp_responsavel_tecnico == 0 ? 'TÉCNICO' : 'ENGENHEIRO' ?></td>
									</tr>
								</tbody>
							</table>
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="visto">
						<button style="float: right;" data-toggle="modal" href="#modalCadastroVisto" class="btn btn-primary"
								type="button" id="novoVisto">Inserir Visto
						</button>
						<div id="listaEstados">
							<table class="table table-striped" style="width: 700px;">
								<thead>
								<tr>
									<th>Sigla</th>
									<th>Estado</th>
									<th>Visto</th>
								</tr>
								</thead>
								<tbody id="tbodyEmpresa">
								<?php foreach ($this->arrEstados as $estado):
									?>
									<tr>
										<td><?php echo $estado['sg_estado']?></td>
										<td><?php echo $estado['no_estado']?></td>
										<td id="tr_<?php echo $estado['co_estado']?>">
											<?php if( in_array($estado['co_estado'], $this->arrVisto) ):?>
												<?php echo '<img src="'.$this->baseUrl().'/images/checked.png">';?>
											<?php endif;?>
										</td>
									</tr>
								<?php endforeach; ?>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane fade" id="anuidade">
						<button style="float: right; margin-right: 10px;" data-toggle="modal" href="#modalCadastroPagamento"
								class="btn btn-primary" type="button" id="novoPagamento">Inserir Pagamento
						</button>
						<div class="modal-header">
							<table class="table table-striped" style="width: 700px;">
								<thead>
								<tr>
									<th>Arquivo</th>
								</tr>
								</thead>
								<tbody id="tbodyEmpresa">
								<?php foreach ($this->arrAnuidade as $anuidade):

									$caminho = Zend_Registry::get('config')->sistema->url . 'download/get/arquivo/' . $anuidade['no_arquivo'] . '/path/anuidade/filename/' . $anuidade['no_arquivo'];
									?>
									<tr id="socio_<?php echo $key ?>">
										<td><a href="<?php echo $caminho ?>"><?php echo $anuidade['ds_lbl_arquivo'] ?></a></td>
									</tr>
								<?php endforeach; ?>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane fade" id="empresa">
						<div style="margin-left: 20px;">
							<div class="modal-header">
							<table class="table table-striped" style="width: 700px;">
								<thead>
								<tr>
									<th>CNPJ</th>
									<th>Razão Social</th>
									<th>Telefone</th>
								</tr>
								</thead>
								<tbody id="tbodyEmpresa">
								<?php foreach ($this->arrEmpresas as $key => $empresa): ?>
									<tr id="socio_<?php echo $key ?>">
										<td><?php echo formataCNPJ($empresa['nu_cnpj']) ?></td>
										<td><?php echo $empresa['no_razao_social'] ?></td>
										<td><?php echo formataTEL($empresa['nu_telefone_1']) ?></td>
									</tr>
								<?php endforeach; ?>
								</tbody>
							</table>
							</div>
						</div>
					</div>
				</div>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->


<!-- Modal -->
<div class="modal" id="modalCadastroVisto">
	<form name="frmCadastroCrea" id="frmCadastroCrea">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Inserir Visto</h4>
				</div>
				<div class="modal-body">
					<p>
						<form name="frmCadastroCrea" id="frmCadastroCrea" class="form-horizontal" action="" method="post">
							<div class="control-group">
								<label class="col-lg-3 control-label" for="tp_responsavel_tecnico">Estado:</label>
								<div class="col-lg-9">
									<?php echo $this->estados(null, 'required="required" style="height:300px"', array('multiselect' => true, 'required'=>true));?>
									<input type="hidden" name="co_responsavel_tecnico" id="co_responsavel_tecnico" value="<?php echo $this->co_responsavel_tecnico?>">
								</div>
							</div>
							<div class="clear">&nbsp;</div>
						</form>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnSalvarVisto" class="btn btn-primary">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->

<!-- Modal -->
<div class="modal" id="modalCadastroPagamento">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Serviço</h4>
				</div>
				<div class="modal-body">
					<p>
					<form name="frmCadastroAnuidadeCrea" id="frmCadastroAnuidadeCrea" class="form-horizontal" action="<?php echo $this->baseUrl()?>/administracao/crea/salvar-anuidade" method="post" enctype="multipart/form-data">
						<div class="control-group">
							<label class="control-label" for="inputNome">Ano:</label>
							<div class="controls">
								<input type="hidden" name="co_responsavel_tecnico" id="co_responsavel_tecnico" value="<?php echo $this->co_responsavel_tecnico?>">
								<input class="ano" type="text" name="nu_ano" id="nu_ano" value="<?php echo date('Y') ?>" readonly="readonly">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="inputNome">Anexar Documento:</label>
							<div class="controls">
								<input type="file" name="no_arquivo" id="no_arquivo" class="btn btn-primary"  required/>
							</div>
						</div>
					</form>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnSalvarArquivo" class="btn btn-primary">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script type="text/javascript">
 $('#frmAcompanhamento').find('input:checkbox').hide();

 $('#listarProtocolos').load( sistemaUrl + 'administracao/acompanhamento/listar-protocolos/co_contrato/' + $('#co_contrato').val() );
function checa( co_checklist ){
	if( $('#check_' + co_checklist ).is(':checked') ){
		$('#img_' + co_checklist ).attr('src', sistemaUrl + 'images/UnChecked.png'); 
		$('#check_' + co_checklist ).removeAttr( 'checked');
	}else{
		$('#img_' + co_checklist ).attr('src', sistemaUrl + 'images/checked.png'); 
		$('#check_' + co_checklist ).attr( 'checked', true);
	}
	
} 
</script>