<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/crea/index.js" type="text/javascript"></script>
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: CREA ::.
		<button style="float: right" data-toggle="modal" href="#modalCadastroResponsavelTecnico" class="btn btn-primary" type="button" id="novoRegistro">Novo Registro</button></h3>
	</div>
</div>
<div id="message_success" class="alert alert-success hide">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading"></h4>
</div>
<div id="message_error" class="alert alert-error hide">
	<a class="close" data-dismiss="alert">×</a>
	<h4 class="alert-heading">Erro!</h4>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Clientes</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
 						<tr>
 							<th>ID</th>
							<th>Nome</th>
							<th>CREA</th>
							<th>Tipo</th>
							<th>Opções</th>
						</tr>
					</thead>
					<tbody>
						<?php
							if( sizeof($this->arrResponsavel) ):
							foreach ($this->arrResponsavel as $crea) :
						?>
						<tr>
							<td><?php echo $crea['co_responsavel_tecnico']?></td>
							<td><?php echo $crea['no_responsavel_tecnico'] ?></td>
							<td><?php echo $crea['nu_registro_crea'] ?></td>
							<td><?php echo $crea['tp_responsavel_tecnico'] == CO_TP_RESPONSAVEL_TECNICO_TECNICO ? 'TÉCNICO' : 'ENGENHEIRO'?></td>
							<td>
							<a title="Editar" href="#" onclick="editar('<?php echo $crea['co_responsavel_tecnico']?>')"><i class="glyphicon glyphicon-edit"></i></a>
							<a title="Visualizar Dados" href="#" onclick="dados(<?php echo $crea['co_responsavel_tecnico']?>);"><i class="glyphicon glyphicon-globe"></i></a>
							<a title="Excluir" href="#" onclick="$('#co_modal').val(<?php echo $crea['co_responsavel_tecnico']?>);$('#confirm-dialog').modal('show');"><i class="glyphicon glyphicon-trash"></i></a>
							</td>
						</tr>
						<?php endforeach;
						else :
						?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
						<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->


<!-- Modal -->
<div class="modal" id="modalCadastroResponsavelTecnico">
	<form name="frmCadastroResponsavelTecnico" id="frmCadastroResponsavelTecnico">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar Serviço</h4>
				</div>
				<div class="modal-body">
					<p>
					<div class="well bs-component">

						<form name="frmCadastroCrea" id="frmCadastroCrea" class="form-horizontal" action="" method="post">
							<div class="control-group">
								<label class="col-lg-3 control-label" for="tp_responsavel_tecnico">Tipo:</label>
								<div class="col-lg-9">
									<input type="hidden" name="co_responsavel_tecnico" id="co_responsavel_tecnico">
									<input type="radio" required name="tp_responsavel_tecnico" value="<?php echo CO_TP_RESPONSAVEL_TECNICO_TECNICO?>"> TÉCNICO
									<input type="radio" required name="tp_responsavel_tecnico" value="<?php echo CO_TP_RESPONSAVEL_TECNICO_ENGENHEIRO?>"> ENGENHEIRO
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="tp_responsavel_tecnico">Recebimento Direto:</label>
								<div class="col-lg-9">
									<input type="checkbox" name="st_recebimento_direto" id="st_recebimento_direto" value="S">
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="nu_registro_crea">Registro:</label>
								<div class="col-lg-9">
									<input class="input-medium" required="required" type="text" name="nu_registro_crea" id="nu_registro_crea" size="20" value="" />
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="nu_registro_crea">Nome:</label>
								<div class="col-lg-9">
									<input class="input-xxlarge" required="required" type="text" name="no_resp_tec" id="no_resp_tec" size="50" value="" />
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="nu_registro_crea">Telefone:</label>
								<div class="col-lg-9">
									<input class="input-medium ddd_telefone" required="required" type="text" name="nu_tel_resp_tec" id="nu_tel_resp_tec" size="20" value="" />
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="nu_registro_crea">E-mail:</label>
								<div class="col-lg-9">
									<input class="input-xxlarge" type="email" required="required" name="ds_email_resp_tec" id="ds_email_resp_tec" size="50" value="" />
								</div>
							</div>
							<div class="clear">&nbsp;</div>
							<div class="control-group">
								<label class="col-lg-3 control-label" for="nu_registro_crea">Whatsapp:</label>
								<div class="col-lg-9">
									<input class="input-medium ddd_telefone" required="required" type="text" name="nu_whatsapp" id="nu_whatsapp" size="20" value="" />
								</div>
							</div>
							<div class="clear">&nbsp;</div>
						</form>
					</div>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" id="btnSalvar" class="btn btn-primary">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->