<?php $this->headScript()->appendFile($this->baseUrl().'/js/administracao/crea/index.js')?>
<style>
.modal {
	width: 800px;
	left: 40%;
}
</style>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: CREA - VISTOS ::.
		<button style="float: right;" data-toggle="modal" href="#modalCadastroVisto" class="btn btn-danger" type="button" id="novoVisto">Visto</button>
		<button style="float: right; margin-right: 10px;" data-toggle="modal" href="#modalCadastroPagamento" class="btn btn-danger" type="button" id="novoPagamento">Pagamento</button></h3>
	</div>
</div>
	<?php if(isset($_SESSION['message'])):?>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo $_SESSION['message']['message']?></h4>
    </div>
    
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message']['message']; ?>
    </div>
    <?php unset($_SESSION['message']);endif;?>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'success' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>CREA</th>
			<th>Tipo</th>
			<th>Área Técnica</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $crea) : 
	?>
		<tr>
			<td><?php echo $crea['co_responsavel_tecnico']?></td>
			<td><?php echo $crea['no_responsavel_tecnico'] ?></td>
			<td><?php echo $crea['nu_registro_regional'] ?></td>
			<td><?php echo $crea['tp_responsavel_tecnico'] == 0 ? 'TÉCNICO' : 'ENGENHEIRO'?></td>
			<td><?php echo $crea['co_area_tecnica'] ?></td>
				<td>
				<a href="#" onclick="editar('<?php echo $crea['co_responsavel_tecnico']?>')"><i class="icon-edit"></i></a>
				<a href="#" onclick="$('#co_modal').val(<?php echo $crea['co_responsavel_tecnico']?>);$('#confirm-dialog').modal('show');"><i class="icon-file"></i></a>
				<a href="#" onclick="vistos(<?php echo $crea['co_responsavel_tecnico']?>);"><i class="icon-globe"></i></a>
				<a href="#" onclick="$('#co_modal').val(<?php echo $crea['co_responsavel_tecnico']?>);$('#confirm-dialog').modal('show');"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
<!-- Modal -->
  <div class="modal hide" id="modalCadastroVisto">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastroVisto').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Visto</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmCadastroCrea" id="frmCadastroCrea" class="form-horizontal" action="" method="post">
					<div class="control-group pj">
						<label class="control-label" for="inputNome">Estado:</label>
						<div class="controls">
							 <?php echo $this->estados(null, 'multiple="multiple" style="height:300px"');?>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<!-- Modal -->
  <div class="modal hide" id="modalCadastroPagamento">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastroPagamento').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Pagamento</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmCadastroCrea" id="frmCadastroCrea" class="form-horizontal" action="" method="post">
					<div class="control-group pj">
						<label class="control-label" for="inputNome">Ano:</label>
						<div class="controls">
							 <input type="hidden" name="co_responsavel_tecnico" id="co_responsavel_tecnico"> 
							 <input class="ano" type="text" name="nu_ano" id="nu_ano" value="">  
						</div>
					</div>
					<div class="control-group pj">
						<label class="control-label" for="inputNome">Estado:</label>
						<div class="controls">
							 <?php echo $this->estados(null, 'multiple="multiple"');?>
						</div>
					</div>
					<div class="control-group pj">
						<label class="control-label" for="inputNome">Registro:</label>
						<div class="controls">
							 <input type="radio" name="tp_registro_crea" id="tp_registro_crea_nacional" value="0"> NACIONAL
							 <input type="radio" name="tp_registro_crea" id="tp_registro_crea_regional" value="1"> REGIONAL
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <div class="modal hide fade" id="confirm-dialog">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3>Confirmar</h3>
	</div>
	<div class="modal-body">Deseja deletar este registro?<input type="hidden" id="co_modal"></div>
	<div class="modal-footer">
		<a style="cursor: pointer" onclick="deletar()" class="btn btn-danger">Ok</a> 
		<a style="cursor: pointer"	class="btn btn-cancel" data-dismiss="modal">Cancelar</a>
	</div>
</div>