<?php $this->headScript()->appendFile($this->baseUrl().'/js/administracao/clientes/index.js')?>
<style>
.modal {
	width: 800px;
	left: 40%;
}
</style>	
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Importação ::.
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h4>Selecione o arquivo a ser importado</h4>
				<form action="" method="post" enctype="multipart/form-data" id="js-upload-form">
					<div class="form-inline">
								<span class="btn btn-success fileinput-button">
									<i class="glyphicon glyphicon-plus"></i>
									<span>Adicionar arquivo</span>
									<input type="file" name="no_arquivo[]">
								</span>
						<button type="button" class="btn btn-primary start" onclick="submit()">
							<i class="glyphicon glyphicon-upload"></i>
							<span>Iniciar upload</span>
						</button>
						<button type="reset" class="btn btn-warning cancel">
							<i class="glyphicon glyphicon-ban-circle"></i>
							<span>Cancelar upload</span>
						</button>
					</div>
				</form>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div><!-- /.col -->
</div><!-- /.row -->
<?php if($this->retorno){?>
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Boletos Atualizados</h3>
				</div><!-- /.box-header  -->
				<div class="box-body">
					<table id="table" class="table table-striped table-bordered">
						<thead>
						<tr>
							<th>Número</th>
							<th>Cliente</th>
							<th>Nosso Número</th>
							<th>Valor</th>
							<th>Valor Pago</th>
							<th>Dt Vencimento</th>
							<th>Dt Pagamento</th>
							<th>Dt Processamento</th>
						</tr>
						</thead>
						<tbody>
						<?php
							foreach ($this->retorno as $boleto) :
								?>
								<tr>
									<td><?php echo $boleto['nu_documento']?></td>
									<td><?php echo limitarTexto($boleto['no_razao_social'], 50)?></td>
									<td><?php echo $boleto['nu_nosso_numero']?></td>
									<td><?php echo 'R$ '.moeda( $boleto['ds_valor'] )?></td>
									<td><?php echo 'R$ '.moeda( $boleto['ds_valor_pago'] )?></td>
									<td><?php echo retornaDmy( $boleto['dt_vencimento'] );?></td>
									<td><?php echo retornaDmy( $boleto['dt_ocorrencia'] ) ?></td>
									<td><?php echo retornaDmy( $boleto['dt_processamento'] ) ?></td>
								</tr>
							<?php endforeach;?>
						</tbody>
					</table>
				</div><!-- /.box-body -->
			</div><!-- /.box -->
		</div><!-- /.col -->
	</div><!-- /.row -->
<?php }?>
