<?php $this->headScript()->appendFile($this->baseUrl().'/js/provedor/index.js')?>	
<style>
.modal {
	width: 800px;
	left: 40%;
}
</style>
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Provedores ::.<button style="float: right" class="btn btn-danger" type="button" id="novoRegistro">Novo Registro</button></h3>
	</div>
</div>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo $_SESSION['message']?></h4>
    </div>
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message'];?>
    </div>
    
    <script type="text/javascript">
   		<?php if( $this->msg == 'sucesso' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php 
	    endif;
	    unset($_SESSION['message']);	    
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>
	
<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>Nome Fantasia</th>
			<th>E-mail</th>
			<th>Telefone</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $provedor) : 
	?>
		<tr>
			<td><?php echo $provedor['id']?></td>
			<td><?php echo $provedor['nome']?></td>
			<td><?php echo $provedor['nome_fantasia']?></td>
			<td><?php echo $provedor['email']?></td>
			<td><?php echo utf8_decode( $provedor['fone_1'] )?></td>
			<td>
				<a onclick="$('#co_modal').val(<?php echo $provedor['id']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-search"></i></a>
				<a onclick="editar('<?php echo $provedor['id']?>')" href="#"><i class="icon-edit"></i></a>
				<a onclick="$('#co_modal').val(<?php echo $provedor['id']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
<!-- Modal -->
  <div class="modal fade" id="modalCadastro">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastro').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Provedores</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmCadastroProvedor" id="frmCadastroProvedor" class="form-horizontal" method="post"  action="">
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputEmail">Nome: <span style="color:red">*&nbsp;</span> </label>
						<div class="col-lg-10">
							<input type="text" style="width: 500px;" class="" required="required" name="nome" id="nome" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Nome Fantasia: </label>
						<div class="col-lg-10">
							<input type="text" style="width: 500px;" name="nome_fantasia" id="nome_fantasia" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Tipo: </label>
						<div class="col-lg-10">
							<input type="radio" name="tipo" value="1"> Pessoa Física
							<input type="radio" name="tipo" value="2"> Pessoa Jurídica
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword" data-mask="999.999.999-99">CPF: </label>
						<div class="col-lg-10">
							<input type="text" name="cpf" id="cpf" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">CNPJ: <span style="color:red">*&nbsp;</span></label>
						<div class="col-lg-10">
							<input type="text" name="cnpj" required="required" id="cnpj" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Endereço: </label>
						<div class="col-lg-10">
							<input type="text" style="width: 500px;" name="endereco" id="endereco" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>	
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Estado: </label>
						<div class="col-lg-10">
							<select id="estado" name="estado">
		                                  <option value="">- -</option>
		                                  <option value="AC">AC</option> 
		                                  <option value="AL">AL</option> 
		                                  <option value="AM">AM</option> 
		                                  <option value="AP">AP</option> 
		                                  <option value="BA">BA</option> 
		                                  <option value="CE">CE</option> 
		                                  <option value="DF">DF</option> 
		                                  <option value="ES">ES</option> 
		                                  <option value="GO">GO</option> 
		                                  <option value="MA">MA</option> 
		                                  <option value="MG">MG</option> 
		                                  <option value="MS">MS</option> 
		                                  <option value="MT">MT</option> 
		                                  <option value="PA">PA</option> 
		                                  <option value="PB">PB</option> 
		                                  <option value="PE">PE</option> 
		                                  <option value="PI">PI</option> 
		                                  <option value="PR">PR</option> 
		                                  <option value="RJ">RJ</option> 
		                                  <option value="RN">RN</option> 
		                                  <option value="RO">RO</option> 
		                                  <option value="RR">RR</option> 
		                                  <option value="RS">RS</option> 
		                                  <option value="SC">SC</option> 
		                                  <option value="SE">SE</option> 
		                                  <option value="SP">SP</option> 
		                                  <option value="TO">TO</option>
		                                </select>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Cidade: </label>
						<div class="col-lg-10">
							<input type="text" style="width: 500px;" name="cidade" id="cidade" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">CEP: </label>
						<div class="col-lg-10">
							<input type="text" name="cep" id="cep" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Telefone: <span style="color:red">*&nbsp;</span></label>
						<div class="col-lg-10">
							<input type="text" name="telefone" required="required" id="telefone" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">0800: </label>
						<div class="col-lg-10">
							<input type="text" name="0800" id="0800" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">E-mail <span style="color:red">*&nbsp;</span>: </label>
						<div class="col-lg-10">
							<input type="email" style="width: 500px;" name="email" id="email" required="required" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">MSN ou Skype : </label>
						<div class="col-lg-10">
							<input type="email" style="width: 500px;" name="msnskype" id="msnskype" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<label class="col-lg-2 control-label" for="inputPassword">Técnico Responsável : </label>
						<div class="col-lg-10">
							<input type="email" style="width: 500px;" name="tecnico" id="tecnico" value="">
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<span>Plano:</span>
					</div>
					<div class="form-group">
						<div class="col-lg-10">
							<textarea id="plano" name="plano"  rows="3" class="form-control"></textarea>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<span>Ata:</span>
					</div>
					<div class="form-group">
						<div class="col-lg-10">
							<textarea id="ata" name="ata"  rows="3" class="form-control"></textarea>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<span>Observação:</span>
					</div>
					<div class="form-group">
						<div class="col-lg-10">
							<textarea id="obs" name="obs"  rows="3" class="form-control"></textarea>
						</div>
					</div>
					<div class="clear">&nbsp;</div>
					<div class="form-group">
						<div class="col-lg-10 col-lg-offset-2">
							<button class="btn btn-default">Cancelar</button>
							<button class="btn btn-primary" type="submit">Salvar</button>
						</div>
					</div>
			</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal --> 