<?php $this->headScript()->appendFile($this->baseUrl().'/js/clientes/index.js')?>
<style>
.modal {
	width: 800px;
	left: 40%;
}
</style>
<div class="navbar">
	<div class="navbar-inner">
		<h3>.:: Clientes ::.<button style="float: right" class="btn btn-danger" type="button" id="novoRegistro">Novo Registro</button></h3>
	</div>
</div>
	<div id="message_success" class="alert alert-success hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><?php echo $_SESSION['message']?></h4>
    </div>
	<div id="message_error" class="alert alert-error hide">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Erro!</h4>
    	<?php echo $_SESSION['message'];?>
    </div>

    <script type="text/javascript">
   		<?php if( $this->msg == 'sucesso' ) : ?>
			$('#message_success').show('slide').delay(8000).hide('slide');
		<?php elseif( $this->msg == 'erro' ) :?>
			$('#message_error').show('slide').delay(8000).hide('slide');
	    <?php
	    endif;
	    unset($_SESSION['message']);
	    ?>
	    var data = '<?php echo $this->data;?>';
	</script>

<table id="table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>E-mail</th>
			<th>Telefone</th>
			<th>Provedor</th>
			<th>Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php
	if( sizeof($this->paginator) ):
		foreach ($this->paginator as $cliente) :
	?>
		<tr>
			<td><?php echo $cliente['id']?></td>
			<td><?php echo $cliente['nome']?></td>
			<td><?php echo $cliente['email']?></td>
			<td><?php echo utf8_decode( $cliente['fone_1'] )?></td>
			<td><?php echo $cliente['no_provedor']?></td>
			<td>
				<a onclick="abrirChamado(<?php echo $cliente['id']?>, <?php echo $cliente['id_provedor']?>);" href="#"><i class="icon-headphones"></i></a>
				<a onclick="$('#co_modal').val(<?php echo $cliente['id']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-search"></i></a>
				<a onclick="editar('<?php echo $cliente['id']?>')" href="#"><i class="icon-edit"></i></a>
				<a onclick="$('#co_modal').val(<?php echo $cliente['id']?>);$('#confirm-dialog').modal('show');" href="#"><i class="icon-trash"></i></a>
			</td>
		</tr>
	<?php endforeach;
	else :
	?>
		<tr class="alert alert-block alert-error fade in">
			<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
		</tr>
	<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginator; ?>
<!-- Modal -->
  <div class="modal fade" id="modalCadastro">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" onclick="$('#modalCadastro').modal('hide');" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modaltitle" class="modal-title">Cadastro de Cliente</h4>
        </div>
        <div id="modalbody" class="modal-body">
				<form name="frmCategororia" id="frmCategororia" class="form-horizontal" action="" method="post">
					<div class="control-group">
						<label class="control-label" for="inputNome">Nome:</label>
						<div class="controls">
							<input name="nome" class="input-xxlarge" id="nome" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Nome Fantasia:</label>
						<div class="controls">
							<input name="nome_fantasia" class="input-xxlarge" id="nome_fantasia" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Tipo:</label>
						<div class="controls">
							<input type="radio" class="input" id="pf" value="pf" style="vertical-align: middle;" /> Pessoa Física &nbsp;&nbsp;
                            <input type="radio" class="input" name="tipo" id="pj" value="pj" style="vertical-align: middle;" /> Pessoa Jurídica
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">CPF:</label>
						<div class="controls">
							<input name="cpf" class="input-medium" id="cpf" type="text" size="30" maxlength="15" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">CNPJ:</label>
						<div class="controls">
							<input name="cnpj" class="input-medium" id="cnpj" type="text" size="30" maxlength="15" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Endereço:</label>
						<div class="controls">
							<input name="endereco" class="input-xxlarge" id="endereco" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Estado:</label>
						<div class="controls">
							<select class="input-small" name="estado" id="estado">
                                  <option value="">- -</option>
                                  <option value="AC">AC</option>
                                  <option value="AL">AL</option>
                                  <option value="AM">AM</option>
                                  <option value="AP">AP</option>
                                  <option value="BA">BA</option>
                                  <option value="CE">CE</option>
                                  <option value="DF">DF</option>
                                  <option value="ES">ES</option>
                                  <option value="GO">GO</option>
                                  <option value="MA">MA</option>
                                  <option value="MG">MG</option>
                                  <option value="MS">MS</option>
                                  <option value="MT">MT</option>
                                  <option value="PA">PA</option>
                                  <option value="PB">PB</option>
                                  <option value="PE">PE</option>
                                  <option value="PI">PI</option>
                                  <option value="PR">PR</option>
                                  <option value="RJ">RJ</option>
                                  <option value="RN">RN</option>
                                  <option value="RO">RO</option>
                                  <option value="RR">RR</option>
                                  <option value="RS">RS</option>
                                  <option value="SC">SC</option>
                                  <option value="SE">SE</option>
                                  <option value="SP">SP</option>
                                  <option value="TO">TO</option>
                                </select>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Cidade:</label>
						<div class="controls">
							<input class="input-xlarge" name="cidade" id="cidade" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">CEP:</label>
						<div class="controls">
							 <input class="input-medium" name="cep" id="cep" type="text" size="30" maxlength="15" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Telefone 1:</label>
						<div class="controls">
							 <input class="input-medium" type="text" name="fone_1" id="fone_1" size="20" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Telefone 2:</label>
						<div class="controls">
							 <input class="input-medium" type="text" name="fone_2" id="fone_2" size="20" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">E-mail:</label>
						<div class="controls">
							 <input class="input-xxlarge" name="email" id="email" type="text" size="50" maxlength="100" onKeyUp="javascript: validar_caracter(this)" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Login:</label>
						<div class="controls">
							 <input class="input-large" name="login" id="login" type="text" size="50" maxlength="100" value="" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" for="inputNome">Plano Provedor:</label>
						<div class="controls">
							 <textarea rows="5" class="input-xxlarge" name="plano" id="plano" cols="50"></textarea>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
							<button type="submit" class="btn btn-primary">Salvar</button>
						</div>
					</div>
				</form>
			</div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->