<script src="<?=Zend_Registry::get('config')->caminho->componente?>js/administracao/cnae/index.js" type="text/javascript"></script>
<div id="message_success" class="alert alert-success hide">
	<h4 class="alert-heading"></h4>
</div>
<div id="message_error" class="alert alert-error hide">
	<h4 class="alert-heading">Erro!</h4>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">CNAE</h3>
				<button style="float: right" data-toggle="modal" href="#modalCadastro" class="btn btn-danger" type="button" id="novoRegistro">Novo Registro</button></h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<table id="table" class="table table-striped table-bordered">
					<thead>
					<tr>
						<th>Descrição</th>
						<th>Código</th>
						<th>Sigla</th>
						<th>Opções</th>
					</tr>
					</thead>
					<tbody>
					<?php
					if( sizeof($this->arrCnae) ):
						foreach ($this->arrCnae as $cnae) :
							?>
							<tr>
								<td><?php echo $cnae['ds_cnae'] ?></td>
								<td><?php echo $cnae['cod_cnae'] ?></td>
								<td><?php echo $cnae['sg_cnae']?></td>
								<td>
									<a title="Visualizar" onclick="visualizar('<?php echo $cnae['co_cnae']?>')" href="#"><i class="glyphicon glyphicon-search"></i></a>
									<a title="Editar" onclick="editar('<?php echo $cnae['co_cnae']?>)" href="#"><i class="glyphicon glyphicon-edit"></i></a>
									<a title="Excluir" onclick="excluir(<?php echo $cnae['co_cnae']?>)" href="#"><i class="glyphicon glyphicon-trash"></i></a>
								</td>
							</tr>
						<?php endforeach;
					else :
						?>
						<tr class="alert alert-block alert-error fade in">
							<td colspan="7"><div align="center">Nenhum resultado encontrado!</div></td>
						</tr>
					<?php endif;?>
					</tbody>
				</table>
			</div><!-- /.box-body -->
		</div><!-- /.box -->


	</div><!-- /.col -->
</div><!-- /.row -->

<!-- Modal -->
<div class="modal" id="modalCadastro">
	<form name="frmCadCnae" id="frmCadCnae" class="form-horizontal" action="" method="post">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tituloModalExistente">Cadastrar CNAE</h4>
				</div>
				<div class="modal-body">
					<p>
						<div class="control-group">
							<label class="col-lg-3 control-label" for="inputNome">Descrição: <span style="color:red">*</span></label>
							<div class="col-lg-9">
								<input type="hidden" name="co_servico" id="co_cnae">
								<input type="text" required="required" name="ds_cnae" id="ds_cnae">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-3 control-label" for="inputNome">Código: <span style="color:red">*</span></label>
							<div class="col-lg-9">
								<input type="text" required="required" name="cod_cnae" id="cod_cnae">
							</div>
						</div>
						<div class="clear">&nbsp;</div>
						<div class="control-group">
							<label class="col-lg-3 control-label" for="inputNome">Sigla: <span style="color:red">*</span></label>
							<div class="col-lg-9">
								<input type="text" required="required" name="sg_cnae" id="sg_cnae">
							</div>
						</div>
					</p>
					<div class="clear">&nbsp;</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Cancelar</button>
					<button type="submit" class="btn btn-primary" id="btnSalvar">Salvar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->



  <div class="modal" id="confirm-dialog">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">x</a>
		<h3>Confirmar</h3>
	</div>
	<div class="modal-body">Deseja deletar este registro?<input type="hidden" id="co_modal"></div>
	<div class="modal-footer">
		<a style="cursor: pointer" onclick="deletar()" class="btn btn-danger">Ok</a>
		<a style="cursor: pointer"	class="btn btn-cancel" data-dismiss="modal">Cancelar</a>
	</div>
</div>