<ul class="sidebar-menu">
    <li class="header">MÓDULOS</li>
    <li>
        <a href="<?php echo Zend_Registry::get('config')->caminho->componente?>administracao/index">
            <i class="ion ion-headphone"></i> <span>Administração</span>
        </a>
    </li>
    <li>
        <a href="<?php echo Zend_Registry::get('config')->caminho->componente?>financeiro/contrato">
            <i class="ion ion-mic-a"></i> <span>Financeiro</span>
        </a>
    </li>
    <li>
        <a href="<?php echo Zend_Registry::get('config')->caminho->componente?>posoutorga/index">
            <i class="ion ion-mic-a"></i> <span>Pós Outorga</span>
        </a>
    </li>
    <li>
        <a href="<?php echo Zend_Registry::get('config')->caminho->componente?>pqs/index">
            <i class="ion ion-mic-a"></i> <span>PQS</span>
        </a>
    </li>
</ul>